### Importing Necessaries

In [222]:
import os
import math
import re
import numpy as np 
import pandas as pd 
import matplotlib.pyplot as plt 
import seaborn as sns
from sklearn.experimental import enable_iterative_imputer

#for preprocessing and Feature engineering
from sklearn.impute import (
    SimpleImputer,
    KNNImputer
)

from sklearn.feature_selection import (
    SelectKBest,
    SelectPercentile,
    RFE,
    RFECV,
    VarianceThreshold
)

from sklearn.preprocessing import (
    OneHotEncoder,
    MinMaxScaler,
    StandardScaler,
    RobustScaler,
    Normalizer,
    PolynomialFeatures,
    OrdinalEncoder,
    LabelEncoder,
    KBinsDiscretizer,
    FunctionTransformer
)

#Model Selection and Evaluation

from sklearn.model_selection import (
    train_test_split,
    cross_val_predict,
    cross_val_score,
    GridSearchCV,
    RandomizedSearchCV,
    StratifiedKFold,
    KFold,
    cross_validate
)

from sklearn.metrics import (
    accuracy_score,
    precision_recall_curve,
    roc_auc_score,
    mean_absolute_error,
    mean_absolute_percentage_error,
    mean_squared_error,
    root_mean_squared_error,
    confusion_matrix,
    r2_score,
    classification_report,
    f1_score,
    recall_score,
    explained_variance_score,
    precision_score
)

#fro regression
from sklearn.linear_model import (
    LinearRegression,
    Ridge,
    Lasso,
    ElasticNet,
    BayesianRidge,
    SGDRegressor,
    PassiveAggressiveRegressor
)

from sklearn.tree import(
    DecisionTreeRegressor
)

from sklearn.ensemble import (
    RandomForestRegressor,
    GradientBoostingRegressor,
    AdaBoostRegressor,
    ExtraTreesRegressor,
    BaggingRegressor
)

from sklearn.svm import (
    SVR,
    LinearSVR
)

from sklearn.neighbors import(
    KNeighborsRegressor
)

from sklearn.neural_network import(
    MLPRegressor,
    _multilayer_perceptron
)

#for Classification
from sklearn.linear_model import(
    LogisticRegression,
    RidgeClassifier,
    Perceptron,
    PassiveAggressiveClassifier,
    SGDClassifier
)

from sklearn.tree import DecisionTreeClassifier

from sklearn.ensemble import(
    RandomForestClassifier,
    GradientBoostingClassifier,
    AdaBoostClassifier,
    ExtraTreesClassifier,
    BaggingClassifier
)

from sklearn.svm import (
    SVC,
    LinearSVC,
    NuSVC
)

from sklearn.neighbors import KNeighborsClassifier

from sklearn.naive_bayes import (
    GaussianNB,
    MultinomialNB,
    BernoulliNB,
    CategoricalNB,
    ComplementNB
)

from sklearn.neural_network import MLPClassifier

from sklearn.discriminant_analysis import(
    QuadraticDiscriminantAnalysis,
    LinearDiscriminantAnalysis
)

from sklearn.impute import IterativeImputer

from sklearn.compose import ColumnTransformer

from sklearn.pipeline import Pipeline

import scipy.stats as stas

from scipy.stats import (
    anderson,
    jarque_bera,
    shapiro,
    normaltest,
    kstest
)

from statsmodels.stats.diagnostic import lilliefors

from scipy.stats import zscore

from sklearn.feature_extraction import FeatureHasher

from sklearn.base import BaseEstimator, TransformerMixin
from sklearn.model_selection import train_test_split, GridSearchCV
from sklearn.compose import ColumnTransformer, TransformedTargetRegressor
from sklearn.feature_selection import SelectFromModel
from sklearn.base import BaseEstimator, TransformerMixin

### Loading Datasets

In [223]:
path = os.path.join('..','data', 'raw', 'used_cars.csv')
print(path)

..\data\raw\used_cars.csv

In [224]:
df=pd.read_csv(path)

#### Basic Initial Inspection

In [225]:
pd.set_option('display.max_rows', None)
pd.set_option('display.max_columns', None)
pd.set_option('display.max_colwidth', None)
df.head(1)

,brand,model,model_year,milage,fuel_type,engine,transmission,ext_col,int_col,accident,clean_title,price
0,Ford,Utility Police Interceptor Base,2013,"51,000 mi.",E85 Flex Fuel,300.0HP 3.7L V6 Cylinder Engine Flex Fuel Capability,6-Speed A/T,Black,Black,At least 1 accident or damage reported,Yes,"$10,300"

In [226]:
df.tail(1)

,brand,model,model_year,milage,fuel_type,engine,transmission,ext_col,int_col,accident,clean_title,price
4008,BMW,X3 xDrive30i,2020,"43,000 mi.",Gasoline,248.0HP 2.0L 4 Cylinder Engine Gasoline Fuel,A/T,Gray,Brown,At least 1 accident or damage reported,Yes,"$40,000"

In [227]:
df.sample()

,brand,model,model_year,milage,fuel_type,engine,transmission,ext_col,int_col,accident,clean_title,price
2748,Nissan,Xterra S,2012,"80,000 mi.",Gasoline,261.0HP 4.0L V6 Cylinder Engine Gasoline Fuel,A/T,Black,Gray,None reported,Yes,"$14,800"

In [228]:
df.describe()

        model_year
count  4009.000000
mean   2015.515590
std       6.104816
min    1974.000000
25%    2012.000000
50%    2017.000000
75%    2020.000000
max    2024.000000

In [229]:
df.describe(include='all')

,brand,model,model_year,milage,fuel_type,engine,transmission,ext_col,int_col,accident,clean_title,price
count,4009,4009,4009.000000,4009,3839,4009,4009,4009,4009,3896,3413,4009
unique,57,1898,NaN,2818,7,1146,62,319,156,2,1,1569
top,Ford,M3 Base,NaN,"110,000 mi.",Gasoline,2.0L I4 16V GDI DOHC Turbo,A/T,Black,Black,None reported,Yes,"$15,000"
freq,386,30,NaN,16,3309,52,1037,905,2025,2910,3413,39
mean,NaN,NaN,2015.515590,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
std,NaN,NaN,6.104816,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
min,NaN,NaN,1974.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25%,NaN,NaN,2012.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
50%,NaN,NaN,2017.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
75%,NaN,NaN,2020.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
max,NaN,NaN,2024.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [230]:
print(f"The memory consumed in memory is {(df.memory_usage(deep=True)/(1024*1024)).sum():.3f}MB")

The memory consumed in memory is 0.872MB

In [231]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 4009 entries, 0 to 4008
Data columns (total 12 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   brand         4009 non-null   str
 1   model         4009 non-null   str
 2   model_year    4009 non-null   int64
 3   milage        4009 non-null   str
 4   fuel_type     3839 non-null   str
 5   engine        4009 non-null   str
 6   transmission  4009 non-null   str
 7   ext_col       4009 non-null   str
 8   int_col       4009 non-null   str
 9   accident      3896 non-null   str
 10  clean_title   3413 non-null   str
 11  price         4009 non-null   str
dtypes: int64(1), str(11)
memory usage: 892.6 KB

In [232]:
df.head()

,brand,model,model_year,milage,fuel_type,engine,transmission,ext_col,int_col,accident,clean_title,price
0,Ford,Utility Police Interceptor Base,2013,"51,000 mi.",E85 Flex Fuel,300.0HP 3.7L V6 Cylinder Engine Flex Fuel Capability,6-Speed A/T,Black,Black,At least 1 accident or damage reported,Yes,"$10,300"
1,Hyundai,Palisade SEL,2021,"34,742 mi.",Gasoline,3.8L V6 24V GDI DOHC,8-Speed Automatic,Moonlight Cloud,Gray,At least 1 accident or damage reported,Yes,"$38,005"
2,Lexus,RX 350 RX 350,2022,"22,372 mi.",Gasoline,3.5 Liter DOHC,Automatic,Blue,Black,None reported,NaN,"$54,598"
3,INFINITI,Q50 Hybrid Sport,2015,"88,900 mi.",Hybrid,354.0HP 3.5L V6 Cylinder Engine Gas/Electric Hybrid,7-Speed A/T,Black,Black,None reported,Yes,"$15,500"
4,Audi,Q3 45 S line Premium Plus,2021,"9,835 mi.",Gasoline,2.0L I4 16V GDI DOHC Turbo,8-Speed Automatic,Glacier White Metallic,Black,None reported,NaN,"$34,999"

In [233]:
df['milage'] = (
    df['milage']
    .str.replace(',','')
    .str.replace('mi.','')
    .astype(float)
)

In [234]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 4009 entries, 0 to 4008
Data columns (total 12 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   brand         4009 non-null   str
 1   model         4009 non-null   str
 2   model_year    4009 non-null   int64
 3   milage        4009 non-null   float64
 4   fuel_type     3839 non-null   str
 5   engine        4009 non-null   str
 6   transmission  4009 non-null   str
 7   ext_col       4009 non-null   str
 8   int_col       4009 non-null   str
 9   accident      3896 non-null   str
 10  clean_title   3413 non-null   str
 11  price         4009 non-null   str
dtypes: float64(1), int64(1), str(10)
memory usage: 853.2 KB

In [235]:
df['price'] = (
    df['price']
    .str.replace('$','')
    .str.replace(',','')
    .astype(float)
)

In [236]:
df.head()

,brand,model,model_year,milage,fuel_type,engine,transmission,ext_col,int_col,accident,clean_title,price
0,Ford,Utility Police Interceptor Base,2013,51000.0,E85 Flex Fuel,300.0HP 3.7L V6 Cylinder Engine Flex Fuel Capability,6-Speed A/T,Black,Black,At least 1 accident or damage reported,Yes,10300.0
1,Hyundai,Palisade SEL,2021,34742.0,Gasoline,3.8L V6 24V GDI DOHC,8-Speed Automatic,Moonlight Cloud,Gray,At least 1 accident or damage reported,Yes,38005.0
2,Lexus,RX 350 RX 350,2022,22372.0,Gasoline,3.5 Liter DOHC,Automatic,Blue,Black,None reported,NaN,54598.0
3,INFINITI,Q50 Hybrid Sport,2015,88900.0,Hybrid,354.0HP 3.5L V6 Cylinder Engine Gas/Electric Hybrid,7-Speed A/T,Black,Black,None reported,Yes,15500.0
4,Audi,Q3 45 S line Premium Plus,2021,9835.0,Gasoline,2.0L I4 16V GDI DOHC Turbo,8-Speed Automatic,Glacier White Metallic,Black,None reported,NaN,34999.0

In [237]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 4009 entries, 0 to 4008
Data columns (total 12 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   brand         4009 non-null   str
 1   model         4009 non-null   str
 2   model_year    4009 non-null   int64
 3   milage        4009 non-null   float64
 4   fuel_type     3839 non-null   str
 5   engine        4009 non-null   str
 6   transmission  4009 non-null   str
 7   ext_col       4009 non-null   str
 8   int_col       4009 non-null   str
 9   accident      3896 non-null   str
 10  clean_title   3413 non-null   str
 11  price         4009 non-null   float64
dtypes: float64(2), int64(1), str(9)
memory usage: 825.9 KB

In [238]:
df['Accident_Occurred'] = (
    df['accident']
    .apply(lambda x: "NO" if x=='None reported' else "YES")
)

In [239]:
df.head()

,brand,model,model_year,milage,fuel_type,engine,transmission,ext_col,int_col,accident,clean_title,price,Accident_Occurred
0,Ford,Utility Police Interceptor Base,2013,51000.0,E85 Flex Fuel,300.0HP 3.7L V6 Cylinder Engine Flex Fuel Capability,6-Speed A/T,Black,Black,At least 1 accident or damage reported,Yes,10300.0,YES
1,Hyundai,Palisade SEL,2021,34742.0,Gasoline,3.8L V6 24V GDI DOHC,8-Speed Automatic,Moonlight Cloud,Gray,At least 1 accident or damage reported,Yes,38005.0,YES
2,Lexus,RX 350 RX 350,2022,22372.0,Gasoline,3.5 Liter DOHC,Automatic,Blue,Black,None reported,NaN,54598.0,NO
3,INFINITI,Q50 Hybrid Sport,2015,88900.0,Hybrid,354.0HP 3.5L V6 Cylinder Engine Gas/Electric Hybrid,7-Speed A/T,Black,Black,None reported,Yes,15500.0,NO
4,Audi,Q3 45 S line Premium Plus,2021,9835.0,Gasoline,2.0L I4 16V GDI DOHC Turbo,8-Speed Automatic,Glacier White Metallic,Black,None reported,NaN,34999.0,NO

In [240]:
df['Engine_Capacity'] = (
    df['engine']
    .str.extract(r'(\d+\.\d+L|\d+L|\d+\.\d+\s+Liter|\d+\s+Liter)')
)

In [241]:
df.head()

,brand,model,model_year,milage,fuel_type,engine,transmission,ext_col,int_col,accident,clean_title,price,Accident_Occurred,Engine_Capacity
0,Ford,Utility Police Interceptor Base,2013,51000.0,E85 Flex Fuel,300.0HP 3.7L V6 Cylinder Engine Flex Fuel Capability,6-Speed A/T,Black,Black,At least 1 accident or damage reported,Yes,10300.0,YES,3.7L
1,Hyundai,Palisade SEL,2021,34742.0,Gasoline,3.8L V6 24V GDI DOHC,8-Speed Automatic,Moonlight Cloud,Gray,At least 1 accident or damage reported,Yes,38005.0,YES,3.8L
2,Lexus,RX 350 RX 350,2022,22372.0,Gasoline,3.5 Liter DOHC,Automatic,Blue,Black,None reported,NaN,54598.0,NO,3.5 Liter
3,INFINITI,Q50 Hybrid Sport,2015,88900.0,Hybrid,354.0HP 3.5L V6 Cylinder Engine Gas/Electric Hybrid,7-Speed A/T,Black,Black,None reported,Yes,15500.0,NO,3.5L
4,Audi,Q3 45 S line Premium Plus,2021,9835.0,Gasoline,2.0L I4 16V GDI DOHC Turbo,8-Speed Automatic,Glacier White Metallic,Black,None reported,NaN,34999.0,NO,2.0L

In [242]:
df['Horse_Power'] =(
    df['engine']
    .str.extract(r'(\d+\.\d+HP|\d+HP)')
)

In [243]:
df.head()

,brand,model,model_year,milage,fuel_type,engine,transmission,ext_col,int_col,accident,clean_title,price,Accident_Occurred,Engine_Capacity,Horse_Power
0,Ford,Utility Police Interceptor Base,2013,51000.0,E85 Flex Fuel,300.0HP 3.7L V6 Cylinder Engine Flex Fuel Capability,6-Speed A/T,Black,Black,At least 1 accident or damage reported,Yes,10300.0,YES,3.7L,300.0HP
1,Hyundai,Palisade SEL,2021,34742.0,Gasoline,3.8L V6 24V GDI DOHC,8-Speed Automatic,Moonlight Cloud,Gray,At least 1 accident or damage reported,Yes,38005.0,YES,3.8L,NaN
2,Lexus,RX 350 RX 350,2022,22372.0,Gasoline,3.5 Liter DOHC,Automatic,Blue,Black,None reported,NaN,54598.0,NO,3.5 Liter,NaN
3,INFINITI,Q50 Hybrid Sport,2015,88900.0,Hybrid,354.0HP 3.5L V6 Cylinder Engine Gas/Electric Hybrid,7-Speed A/T,Black,Black,None reported,Yes,15500.0,NO,3.5L,354.0HP
4,Audi,Q3 45 S line Premium Plus,2021,9835.0,Gasoline,2.0L I4 16V GDI DOHC Turbo,8-Speed Automatic,Glacier White Metallic,Black,None reported,NaN,34999.0,NO,2.0L,NaN

In [244]:
df['Engine_Capacity'] = (
    df['Engine_Capacity']
    .str.replace('Liter','')
    .str.replace('L','')
    .astype(float)
)

In [245]:
df.head()

,brand,model,model_year,milage,fuel_type,engine,transmission,ext_col,int_col,accident,clean_title,price,Accident_Occurred,Engine_Capacity,Horse_Power
0,Ford,Utility Police Interceptor Base,2013,51000.0,E85 Flex Fuel,300.0HP 3.7L V6 Cylinder Engine Flex Fuel Capability,6-Speed A/T,Black,Black,At least 1 accident or damage reported,Yes,10300.0,YES,3.7,300.0HP
1,Hyundai,Palisade SEL,2021,34742.0,Gasoline,3.8L V6 24V GDI DOHC,8-Speed Automatic,Moonlight Cloud,Gray,At least 1 accident or damage reported,Yes,38005.0,YES,3.8,NaN
2,Lexus,RX 350 RX 350,2022,22372.0,Gasoline,3.5 Liter DOHC,Automatic,Blue,Black,None reported,NaN,54598.0,NO,3.5,NaN
3,INFINITI,Q50 Hybrid Sport,2015,88900.0,Hybrid,354.0HP 3.5L V6 Cylinder Engine Gas/Electric Hybrid,7-Speed A/T,Black,Black,None reported,Yes,15500.0,NO,3.5,354.0HP
4,Audi,Q3 45 S line Premium Plus,2021,9835.0,Gasoline,2.0L I4 16V GDI DOHC Turbo,8-Speed Automatic,Glacier White Metallic,Black,None reported,NaN,34999.0,NO,2.0,NaN

In [246]:
df['Horse_Power'] = (
    df['Horse_Power']
    .str.replace('HP','')
    .astype(float)
)

In [247]:
df.head()

,brand,model,model_year,milage,fuel_type,engine,transmission,ext_col,int_col,accident,clean_title,price,Accident_Occurred,Engine_Capacity,Horse_Power
0,Ford,Utility Police Interceptor Base,2013,51000.0,E85 Flex Fuel,300.0HP 3.7L V6 Cylinder Engine Flex Fuel Capability,6-Speed A/T,Black,Black,At least 1 accident or damage reported,Yes,10300.0,YES,3.7,300.0
1,Hyundai,Palisade SEL,2021,34742.0,Gasoline,3.8L V6 24V GDI DOHC,8-Speed Automatic,Moonlight Cloud,Gray,At least 1 accident or damage reported,Yes,38005.0,YES,3.8,NaN
2,Lexus,RX 350 RX 350,2022,22372.0,Gasoline,3.5 Liter DOHC,Automatic,Blue,Black,None reported,NaN,54598.0,NO,3.5,NaN
3,INFINITI,Q50 Hybrid Sport,2015,88900.0,Hybrid,354.0HP 3.5L V6 Cylinder Engine Gas/Electric Hybrid,7-Speed A/T,Black,Black,None reported,Yes,15500.0,NO,3.5,354.0
4,Audi,Q3 45 S line Premium Plus,2021,9835.0,Gasoline,2.0L I4 16V GDI DOHC Turbo,8-Speed Automatic,Glacier White Metallic,Black,None reported,NaN,34999.0,NO,2.0,NaN

### Handling Missing Values

In [248]:
df.isnull().sum()

brand                  0
model                  0
model_year             0
milage                 0
fuel_type            170
engine                 0
transmission           0
ext_col                0
int_col                0
accident             113
clean_title          596
price                  0
Accident_Occurred      0
Engine_Capacity      219
Horse_Power          808
dtype: int64

In [249]:
missing_info={}
for col in df.columns:
    if df[col].isnull().sum()>0:
        missing_count=(df[col].isnull().sum()/len(df))*100
        missing_info[col]=round(missing_count,2)
print("\n The columns with missing percentage are:\n")
for col,per in missing_info.items():
    print(f"{col}: {per}%")

 The columns with missing percentage are:

fuel_type: 4.24%
accident: 2.82%
clean_title: 14.87%
Engine_Capacity: 5.46%
Horse_Power: 20.15%

In [250]:
df.head()

,brand,model,model_year,milage,fuel_type,engine,transmission,ext_col,int_col,accident,clean_title,price,Accident_Occurred,Engine_Capacity,Horse_Power
0,Ford,Utility Police Interceptor Base,2013,51000.0,E85 Flex Fuel,300.0HP 3.7L V6 Cylinder Engine Flex Fuel Capability,6-Speed A/T,Black,Black,At least 1 accident or damage reported,Yes,10300.0,YES,3.7,300.0
1,Hyundai,Palisade SEL,2021,34742.0,Gasoline,3.8L V6 24V GDI DOHC,8-Speed Automatic,Moonlight Cloud,Gray,At least 1 accident or damage reported,Yes,38005.0,YES,3.8,NaN
2,Lexus,RX 350 RX 350,2022,22372.0,Gasoline,3.5 Liter DOHC,Automatic,Blue,Black,None reported,NaN,54598.0,NO,3.5,NaN
3,INFINITI,Q50 Hybrid Sport,2015,88900.0,Hybrid,354.0HP 3.5L V6 Cylinder Engine Gas/Electric Hybrid,7-Speed A/T,Black,Black,None reported,Yes,15500.0,NO,3.5,354.0
4,Audi,Q3 45 S line Premium Plus,2021,9835.0,Gasoline,2.0L I4 16V GDI DOHC Turbo,8-Speed Automatic,Glacier White Metallic,Black,None reported,NaN,34999.0,NO,2.0,NaN

In [251]:
Categorical_Columns = df.select_dtypes(include=['object','category']).columns
Numerical_Columns = df.select_dtypes(include=['number','int64','int32','float64','float32']).columns

C:\Users\user\AppData\Local\Temp\ipykernel_10928\1596977203.py:1: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  Categorical_Columns = df.select_dtypes(include=['object','category']).columns

In [252]:
df[Categorical_Columns].head()

,brand,model,fuel_type,engine,transmission,ext_col,int_col,accident,clean_title,Accident_Occurred
0,Ford,Utility Police Interceptor Base,E85 Flex Fuel,300.0HP 3.7L V6 Cylinder Engine Flex Fuel Capability,6-Speed A/T,Black,Black,At least 1 accident or damage reported,Yes,YES
1,Hyundai,Palisade SEL,Gasoline,3.8L V6 24V GDI DOHC,8-Speed Automatic,Moonlight Cloud,Gray,At least 1 accident or damage reported,Yes,YES
2,Lexus,RX 350 RX 350,Gasoline,3.5 Liter DOHC,Automatic,Blue,Black,None reported,NaN,NO
3,INFINITI,Q50 Hybrid Sport,Hybrid,354.0HP 3.5L V6 Cylinder Engine Gas/Electric Hybrid,7-Speed A/T,Black,Black,None reported,Yes,NO
4,Audi,Q3 45 S line Premium Plus,Gasoline,2.0L I4 16V GDI DOHC Turbo,8-Speed Automatic,Glacier White Metallic,Black,None reported,NaN,NO

In [253]:
df[Numerical_Columns].head()

   model_year   milage    price  Engine_Capacity  Horse_Power
0        2013  51000.0  10300.0              3.7        300.0
1        2021  34742.0  38005.0              3.8          NaN
2        2022  22372.0  54598.0              3.5          NaN
3        2015  88900.0  15500.0              3.5        354.0
4        2021   9835.0  34999.0              2.0          NaN

In [254]:
missing_info={}
for col in Categorical_Columns:
    if df[col].isnull().sum()>0:
        missing_count=(df[col].isnull().sum()/len(df))*100
        missing_info[col]=round(missing_count,2)
print("\n The Categorical columns with missing percentage is:\n")
for col,per in missing_info.items():
    print(f"{col}: {per}%")

 The Categorical columns with missing percentage is:

fuel_type: 4.24%
accident: 2.82%
clean_title: 14.87%

In [255]:
df['clean_title'].value_counts()

clean_title
Yes    3413
Name: count, dtype: int64

In [256]:
df[['brand', 'clean_title']].head()

      brand clean_title
0      Ford         Yes
1   Hyundai         Yes
2     Lexus         NaN
3  INFINITI         Yes
4      Audi         NaN

In [257]:
df['clean_title']=df['clean_title'].fillna('Unknown')

In [258]:
df['clean_title'].head()

0        Yes
1        Yes
2    Unknown
3        Yes
4    Unknown
Name: clean_title, dtype: str

In [259]:
missing_info={}
for col in Categorical_Columns:
    if df[col].isnull().sum()>0:
        missing_count=(df[col].isnull().sum()/len(df))*100
        missing_info[col]=round(missing_count,2)
print("\n The Categorical columns with missing percentage is:\n")
for col,per in missing_info.items():
    print(f"{col}: {per}%")

 The Categorical columns with missing percentage is:

fuel_type: 4.24%
accident: 2.82%

In [260]:
df[['engine','model','transmission','brand','fuel_type']].head(50)

,engine,model,transmission,brand,fuel_type
0,300.0HP 3.7L V6 Cylinder Engine Flex Fuel Capability,Utility Police Interceptor Base,6-Speed A/T,Ford,E85 Flex Fuel
1,3.8L V6 24V GDI DOHC,Palisade SEL,8-Speed Automatic,Hyundai,Gasoline
2,3.5 Liter DOHC,RX 350 RX 350,Automatic,Lexus,Gasoline
3,354.0HP 3.5L V6 Cylinder Engine Gas/Electric Hybrid,Q50 Hybrid Sport,7-Speed A/T,INFINITI,Hybrid
4,2.0L I4 16V GDI DOHC Turbo,Q3 45 S line Premium Plus,8-Speed Automatic,Audi,Gasoline
5,2.4 Liter,ILX 2.4L,F,Acura,Gasoline
6,292.0HP 2.0L 4 Cylinder Engine Gasoline Fuel,S3 2.0T Premium Plus,6-Speed A/T,Audi,Gasoline
7,282.0HP 4.4L 8 Cylinder Engine Gasoline Fuel,740 iL,A/T,BMW,Gasoline
8,311.0HP 3.5L V6 Cylinder Engine Gasoline Fuel,RC 350 F Sport,6-Speed A/T,Lexus,Gasoline
9,534.0HP Electric Motor Electric Fuel System,Model X Long Range Plus,A/T,Tesla,NaN
10,V6,Rover Range Rover Sport 3.0 Supercharged HST,Automatic,Land,Gasoline
11,715.0HP 5.2L 12 Cylinder Engine Gasoline Fuel,Martin DBS Superleggera,8-Speed A/T,Aston,Gasoline
12,382.0HP 3.0L Straight 6 Cylinder Engine Gasoline Fuel,Supra 3.0 Premium,A/T,Toyota,Gasoline
13,400.0HP 3.0L V6 Cylinder Engine Gasoline Fuel,Aviator Reserve AWD,Transmission w/Dual Shift Mode,Lincoln,Gasoline
14,2.0 Liter Supercharged,F-TYPE,Automatic,Jaguar,Gasoline
15,375.0HP 5.0L 8 Cylinder Engine Gasoline Fuel,Rover LR4 HSE,A/T,Land,Gasoline
16,2.0L I4 16V GDI DOHC Turbo,Metris Base,9-Speed Automatic,Mercedes-Benz,Gasoline
17,305.0HP 3.6L V6 Cylinder Engine Gasoline Fuel,Challenger SXT,A/T,Dodge,Gasoline
18,287.0HP 3.5L V6 Cylinder Engine Gasoline Fuel,350Z Enthusiast,6-Speed M/T,Nissan,Gasoline
19,550.0HP 5.0L 8 Cylinder Engine Gasoline Fuel,F-TYPE R,8-Speed A/T,Jaguar,Gasoline
20,375.0HP 3.5L V6 Cylinder Engine Gasoline Fuel,GV70 3.5T Sport,8-Speed A/T,Genesis,Gasoline
21,120.0HP 2.2L 4 Cylinder Engine Flex Fuel Capability,S-10 LS,A/T,Chevrolet,E85 Flex Fuel
22,3.0 Liter Turbo,440 Gran Coupe 440i xDrive,Automatic,BMW,Gasoline
23,3.5L V6 24V PDI DOHC Twin Turbo,F-150 XLT,Automatic,Ford,Gasoline
24,355.0HP 5.3L 8 Cylinder Engine Gasoline Fuel,Suburban RST,10-Speed A/T,Chevrolet,Gasoline
25,276.0HP 2.0L 4 Cylinder Engine Gasoline Fuel,Elantra N Base,Transmission w/Dual Shift Mode,Hyundai,Gasoline
26,1.8 Liter,Sentra SR,Automatic,Nissan,Gasoline
27,382.0HP 2.0L 4 Cylinder Engine Gasoline Fuel,AMG CLA 45 Base 4MATIC,A/T,Mercedes-Benz,Gasoline
28,445.0HP 4.4L 8 Cylinder Engine Gasoline Fuel,650 Gran Coupe i xDrive,8-Speed A/T,BMW,Gasoline
29,2.0L I4 16V GDI DOHC Turbo Flexible Fuel,Q5 2.0T Premium Plus,8-Speed Automatic,Audi,E85 Flex Fuel
30,362.0HP 3.0L V6 Cylinder Engine Gasoline Fuel,AMG C 43 Base 4MATIC,9-Speed A/T,Mercedes-Benz,Gasoline
31,345.0HP 5.7L 8 Cylinder Engine Gasoline Fuel,Ram 1500 Laramie Mega Cab,A/T,Dodge,Gasoline
32,120 AH,i3 120Ah w/Range Extender,Automatic,BMW,Hybrid
33,276.0HP 3.5L V6 Cylinder Engine Gasoline Fuel,Sorento SX,A/T,Kia,Gasoline
34,383.0HP 5.7L 8 Cylinder Engine Gasoline Fuel,LX 570 Base,8-Speed A/T,Lexus,Gasoline
35,180.0HP 2.4L 4 Cylinder Engine Gasoline Fuel,New Compass Trailhawk,A/T,Jeep,Gasoline
36,3.0 Liter Turbo,340 i,Automatic,BMW,Gasoline
37,211.0HP 2.0L 4 Cylinder Engine Gasoline Fuel,A4 2.0T Premium Plus quattro,8-Speed A/T,Audi,Gasoline
38,173.0HP 2.7L V6 Cylinder Engine Gasoline Fuel,Tucson SE,A/T,Hyundai,Gasoline
39,240.0HP 2.0L 4 Cylinder Engine Gasoline Fuel,Z4 sDrive28i,A/T,BMW,Gasoline
40,552.0HP 6.0L 12 Cylinder Engine Flex Fuel Capability,Continental GTC Base,6-Speed A/T,Bentley,E85 Flex Fuel
41,3.5 Liter SOHC,Passport Elite,Automatic,Honda,Gasoline
42,3.0L V6 Cylinder Engine Diesel Fuel,Sprinter 2500,5-Speed A/T,Dodge,Diesel
43,4.4 Liter DOHC Twin Turbo,M850 i xDrive,Automatic,BMW,Gasoline
44,536.0HP Electric Motor Electric Fuel System,Air Grand Touring,1-Speed A/T,Lucid,NaN
45,310.0HP 3.0L V6 Cylinder Engine Gasoline Fuel,A7 Premium,8-Speed A/T,Audi,Gasoline
46,5.3L V8 16V GDI OHV,Silverado 1500 Custom Trail Boss,Automatic,Chevrolet,Gasoline
47,228.0HP 2.0L 4 Cylinder Engine Gasoline Fuel,Convertible John Cooper Works,6-Speed A/T,MINI,Gasoline
48,268.0HP 3.5L V6 Cylinder Engine Gasoline Fuel,Avalon Touring,A/T,Toyota,Gasoline
49,300.0HP 3.6L V6 Cylinder Engine Gasoline Fuel,Cayenne Platinum Edition,8-Speed A/T,Porsche,Gasoline

In [261]:
df.loc[
    df['engine']
    .str.contains('Electric Motor Electric Fuel System',case=False,na=False),
    ['brand','model','transmission','fuel_type','engine']
    ]

,brand,model,transmission,fuel_type,engine
9,Tesla,Model X Long Range Plus,A/T,NaN,534.0HP Electric Motor Electric Fuel System
44,Lucid,Air Grand Touring,1-Speed A/T,NaN,536.0HP Electric Motor Electric Fuel System
68,Lucid,Air Grand Touring,1-Speed A/T,NaN,536.0HP Electric Motor Electric Fuel System
92,Rivian,R1S Adventure Package,1-Speed A/T,NaN,835.0HP Electric Motor Electric Fuel System
122,Rivian,R1S Adventure Package,A/T,NaN,835.0HP Electric Motor Electric Fuel System
129,Lucid,Air Pure,A/T,NaN,620.0HP Electric Motor Electric Fuel System
155,Tesla,Model 3 Performance,A/T,NaN,455.0HP Electric Motor Electric Fuel System
189,Tesla,Model Y Performance,1-Speed A/T,NaN,455.0HP Electric Motor Electric Fuel System
225,Tesla,Model X Base,A/T,NaN,670.0HP Electric Motor Electric Fuel System
253,Mercedes-Benz,EQS 450 4MATIC,1-Speed A/T,NaN,355.0HP Electric Motor Electric Fuel System
266,Mercedes-Benz,EQS 450+ Base,1-Speed A/T,NaN,329.0HP Electric Motor Electric Fuel System
298,Tesla,Model 3 Standard Range Plus,A/T,NaN,271.0HP Electric Motor Electric Fuel System
346,Tesla,Model X Long Range,1-Speed A/T,NaN,670.0HP Electric Motor Electric Fuel System
397,Rivian,R1S Adventure Package,1-Speed A/T,NaN,835.0HP Electric Motor Electric Fuel System
410,Rivian,R1S Adventure Package,1-Speed A/T,NaN,835.0HP Electric Motor Electric Fuel System
451,Audi,e-tron Prestige,1-Speed A/T,NaN,355.0HP Electric Motor Electric Fuel System
472,Rivian,R1S Adventure Package,A/T,NaN,835.0HP Electric Motor Electric Fuel System
503,Chevrolet,Bolt EUV Premier,A/T,NaN,200.0HP Electric Motor Electric Fuel System
518,Tesla,Model Y Long Range,A/T,NaN,425.0HP Electric Motor Electric Fuel System
526,Rivian,R1S Adventure Package,A/T,NaN,835.0HP Electric Motor Electric Fuel System
529,Tesla,Model Y Long Range,1-Speed A/T,NaN,425.0HP Electric Motor Electric Fuel System
542,Nissan,Leaf S,A/T,NaN,147.0HP Electric Motor Electric Fuel System
543,Nissan,Leaf SL,1-Speed A/T,NaN,107.0HP Electric Motor Electric Fuel System
684,Audi,e-tron Prestige,A/T,NaN,355.0HP Electric Motor Electric Fuel System
687,Chevrolet,Bolt EUV Premier,1-Speed A/T,NaN,200.0HP Electric Motor Electric Fuel System
703,Tesla,Model Y Long Range,A/T,NaN,425.0HP Electric Motor Electric Fuel System
719,Karma,Revero Base,A/T,NaN,403.0HP 2.0L Electric Motor Electric Fuel System
721,Ford,Mustang Mach-E California Route 1,1-Speed A/T,NaN,290.0HP Electric Motor Electric Fuel System
746,Ford,Mustang Mach-E Premium,A/T,NaN,266.0HP Electric Motor Electric Fuel System
752,Ford,Mustang Mach-E Premium,1-Speed A/T,NaN,346.0HP Electric Motor Electric Fuel System
753,FIAT,500e Battery Electric,1-Speed A/T,NaN,111.0HP Electric Motor Electric Fuel System
757,Rivian,R1S Adventure Package,1-Speed A/T,NaN,835.0HP Electric Motor Electric Fuel System
799,Tesla,Model S 70D,A/T,NaN,329.0HP Electric Motor Electric Fuel System
943,Nissan,Leaf SV PLUS,1-Speed A/T,NaN,214.0HP Electric Motor Electric Fuel System
1008,Volvo,C40 Recharge Pure Electric Twin Ultimate,A/T,NaN,402.0HP Electric Motor Electric Fuel System
1047,Tesla,Model X Long Range Plus,1-Speed A/T,NaN,534.0HP Electric Motor Electric Fuel System
1071,Tesla,Model Y Long Range,A/T,NaN,425.0HP Electric Motor Electric Fuel System
1091,Tesla,Model X Base,A/T,NaN,670.0HP Electric Motor Electric Fuel System
1098,BMW,i3 Base w/Range Extender,1-Speed A/T,NaN,170.0HP 0.65L Electric Motor Electric Fuel System
1119,Hyundai,Kona EV SEL,1-Speed A/T,NaN,201.0HP Electric Motor Electric Fuel System
1126,Tesla,Model X P90D,A/T,NaN,691.0HP Electric Motor Electric Fuel System
1139,Kia,EV6 GT-Line,1-Speed A/T,NaN,320.0HP Electric Motor Electric Fuel System
1157,Tesla,Model Y Performance,1-Speed A/T,NaN,455.0HP Electric Motor Electric Fuel System
1203,Rivian,R1S Launch Edition,1-Speed A/T,NaN,835.0HP Electric Motor Electric Fuel System
1212,Tesla,Model Y Long Range,A/T,NaN,425.0HP Electric Motor Electric Fuel System
1230,Tesla,Model Y Long Range,A/T,NaN,425.0HP Electric Motor Electric Fuel System
1235,Nissan,Leaf SL,1-Speed A/T,NaN,107.0HP Electric Motor Electric Fuel System
1247,Tesla,Model Y Long Range,A/T,NaN,425.0HP Electric Motor Electric Fuel System
1250,Audi,Q4 e-tron Sportback Premium,A/T,NaN,295.0HP Electric Motor Electric Fuel System
1293,Tesla,Model 3 Standard Range Plus,A/T,NaN,Electric Motor Electric Fuel System
1330,Rivian,R1S Adventure Package,A/T,NaN,835.0HP Electric Motor Electric Fuel System
1331,Tesla,Model Y Long Range,A/T,NaN,425.0HP Electric Motor Electric Fuel System
1509,Hyundai,IONIQ 5 SE,A/T,NaN,320.0HP Electric Motor Electric Fuel System
1522,Ford,F-150 Lightning XLT,A/T,NaN,563.0HP Electric Motor Electric Fuel System
1534,Tesla,Model X 75D,A/T,NaN,518.0HP Electric Motor Electric Fuel System
1544,Rivian,R1S Launch Edition,1-Speed A/T,NaN,835.0HP Electric Motor Electric Fuel System
1554,Karma,Revero Base,A/T,NaN,403.0HP 2.0L Electric Motor Electric Fuel System
1593,Tesla,Model S P100D,A/T,NaN,518.0HP Electric Motor Electric Fuel System
1598,Tesla,Model X Long Range Plus,A/T,NaN,557.0HP Electric Motor Electric Fuel System
1697,Cadillac,LYRIQ Luxury,A/T,NaN,500.0HP Electric Motor Electric Fuel System
1709,Tesla,Model S P100D,A/T,NaN,518.0HP Electric Motor Electric Fuel System
1788,Tesla,Model S 85D,1-Speed A/T,NaN,422.0HP Electric Motor Electric Fuel System
1836,Rivian,R1S Adventure Package,A/T,NaN,835.0HP Electric Motor Electric Fuel System
1884,Tesla,Model 3 Performance,1-Speed A/T,NaN,271.0HP Electric Motor Electric Fuel System
1888,Tesla,Model S 100D,A/T,NaN,518.0HP Electric Motor Electric Fuel System
1901,Tesla,Model S Performance,1-Speed A/T,NaN,778.0HP Electric Motor Electric Fuel System
1911,Porsche,Taycan Turbo,A/T,NaN,616.0HP Electric Motor Electric Fuel System
1943,Tesla,Model 3 Standard Range Plus,A/T,NaN,Electric Motor Electric Fuel System
2066,Chevrolet,Bolt EV LT,A/T,NaN,200.0HP Electric Motor Electric Fuel System
2102,Tesla,Model 3 Long Range,A/T,NaN,271.0HP Electric Motor Electric Fuel System
2116,Tesla,Model S P100D,1-Speed A/T,NaN,Electric Motor Electric Fuel System
2124,Tesla,Model X Long Range,1-Speed A/T,NaN,518.0HP Electric Motor Electric Fuel System
2181,Tesla,Model 3 Base,A/T,NaN,271.0HP Electric Motor Electric Fuel System
2184,Rivian,R1S Adventure Package,1-Speed A/T,NaN,835.0HP Electric Motor Electric Fuel System
2191,Tesla,Model 3 Performance,1-Speed A/T,NaN,455.0HP Electric Motor Electric Fuel System
2209,Tesla,Model 3 Standard Range Plus,A/T,NaN,Electric Motor Electric Fuel System
2231,Tesla,Model 3 Long Range,A/T,NaN,Electric Motor Electric Fuel System
2233,Rivian,R1T Launch Edition,A/T,NaN,835.0HP Electric Motor Electric Fuel System
2236,Tesla,Model 3 Mid Range,A/T,NaN,271.0HP Electric Motor Electric Fuel System
2250,Tesla,Model 3 Long Range,A/T,NaN,425.0HP Electric Motor Electric Fuel System
2322,Tesla,Model Y Performance,A/T,NaN,455.0HP Electric Motor Electric Fuel System
2343,Tesla,Model 3 Long Range,1-Speed A/T,NaN,271.0HP Electric Motor Electric Fuel System
2345,Tesla,Model Y Long Range,A/T,NaN,425.0HP Electric Motor Electric Fuel System
2407,Rivian,R1S Adventure Package,A/T,NaN,533.0HP Electric Motor Electric Fuel System
2426,Volkswagen,ID.4 Pro S,1-Speed A/T,NaN,295.0HP Electric Motor Electric Fuel System
2451,Tesla,Model S Long Range,1-Speed A/T,NaN,670.0HP Electric Motor Electric Fuel System
2472,Rivian,R1S Launch Edition,1-Speed A/T,NaN,835.0HP Electric Motor Electric Fuel System
2484,Tesla,Model Y Performance,A/T,NaN,455.0HP Electric Motor Electric Fuel System
2492,Tesla,Model Y Performance,1-Speed A/T,NaN,455.0HP Electric Motor Electric Fuel System
2677,Rivian,R1S Adventure Package,A/T,NaN,835.0HP Electric Motor Electric Fuel System
2770,Kia,Niro EV EX,1-Speed A/T,NaN,201.0HP Electric Motor Electric Fuel System
2772,Porsche,Taycan Base,2-Speed A/T,NaN,321.0HP Electric Motor Electric Fuel System
2779,Tesla,Model S Performance,A/T,NaN,416.0HP Electric Motor Electric Fuel System
2795,Mercedes-Benz,EQS 450+ Base,A/T,NaN,329.0HP Electric Motor Electric Fuel System
2870,Tesla,Model Y Performance,A/T,NaN,455.0HP Electric Motor Electric Fuel System
2877,Tesla,Model X P100D,1-Speed A/T,NaN,Electric Motor Electric Fuel System
2952,Ford,Mustang Mach-E Premium,1-Speed A/T,NaN,346.0HP Electric Motor Electric Fuel System
2956,Tesla,Model Y Long Range,A/T,NaN,425.0HP Electric Motor Electric Fuel System
2964,Hyundai,Kona EV SEL,1-Speed A/T,NaN,201.0HP Electric Motor Electric Fuel System
2979,Tesla,Model Y Performance,A/T,NaN,455.0HP Electric Motor Electric Fuel System
2982,Tesla,Model S 85,A/T,NaN,362.0HP Electric Motor Electric Fuel System
2984,Tesla,Model 3 Standard Range,A/T,NaN,271.0HP Electric Motor Electric Fuel System
3033,Porsche,Taycan Base,A/T,NaN,375.0HP Electric Motor Electric Fuel System
3048,Tesla,Model Y Performance,1-Speed A/T,NaN,455.0HP Electric Motor Electric Fuel System
3061,Tesla,Model 3 Long Range,A/T,NaN,Electric Motor Electric Fuel System
3090,BMW,i3 120Ah w/Range Extender,A/T,NaN,170.0HP 0.65L Electric Motor Electric Fuel System
3109,Tesla,Model Y Long Range,A/T,NaN,425.0HP Electric Motor Electric Fuel System
3128,Tesla,Model S 100D,1-Speed A/T,NaN,Electric Motor Electric Fuel System
3134,Tesla,Model X 75D,A/T,NaN,518.0HP Electric Motor Electric Fuel System
3151,Tesla,Model S Long Range Plus,A/T,NaN,557.0HP Electric Motor Electric Fuel System
3164,Tesla,Model Y Long Range,1-Speed A/T,NaN,425.0HP Electric Motor Electric Fuel System
3168,Volkswagen,e-Golf SE,1-Speed A/T,NaN,115.0HP Electric Motor Electric Fuel System
3169,Tesla,Model X Long Range,A/T,NaN,670.0HP Electric Motor Electric Fuel System
3193,Tesla,Model X 75D,A/T,NaN,518.0HP Electric Motor Electric Fuel System
3196,Tesla,Model X Long Range,A/T,NaN,670.0HP Electric Motor Electric Fuel System
3207,Kia,EV6 GT-Line,1-Speed A/T,NaN,320.0HP Electric Motor Electric Fuel System
3224,Ford,Mustang Mach-E GT,1-Speed A/T,NaN,480.0HP Electric Motor Electric Fuel System
3255,BMW,i3 Base,1-Speed A/T,NaN,170.0HP 0.65L Electric Motor Electric Fuel System
3272,Tesla,Model S Long Range,1-Speed A/T,NaN,670.0HP Electric Motor Electric Fuel System
3314,Tesla,Model S 75D,1-Speed A/T,NaN,518.0HP Electric Motor Electric Fuel System
3324,BMW,i3 Base w/Range Extender,A/T,NaN,170.0HP 0.65L Electric Motor Electric Fuel System
3383,Tesla,Model 3 Performance,1-Speed A/T,NaN,455.0HP Electric Motor Electric Fuel System
3399,Tesla,Model X 100D,1-Speed A/T,NaN,518.0HP Electric Motor Electric Fuel System
3417,Porsche,Taycan Base,2-Speed A/T,NaN,375.0HP Electric Motor Electric Fuel System
3425,Tesla,Model X Plaid,A/T,NaN,1020.0HP Electric Motor Electric Fuel System
3427,Tesla,Model S 100D,1-Speed A/T,NaN,518.0HP Electric Motor Electric Fuel System
3468,BMW,i3 94 Ah,1-Speed A/T,NaN,170.0HP 0.65L Electric Motor Electric Fuel System
3502,Ford,Mustang Mach-E GT,1-Speed A/T,NaN,480.0HP Electric Motor Electric Fuel System
3510,Tesla,Model S Plaid,A/T,NaN,1020.0HP Electric Motor Electric Fuel System
3520,Chevrolet,Bolt EV LT,1-Speed A/T,NaN,200.0HP Electric Motor Electric Fuel System
3557,Rivian,R1S Launch Edition,1-Speed A/T,NaN,835.0HP Electric Motor Electric Fuel System
3618,Tesla,Model 3 Long Range,1-Speed A/T,NaN,271.0HP Electric Motor Electric Fuel System
3647,Tesla,Model Y Long Range,1-Speed A/T,NaN,425.0HP Electric Motor Electric Fuel System
3673,Tesla,Model Y Long Range,1-Speed A/T,NaN,425.0HP Electric Motor Electric Fuel System
3682,Tesla,Model S 90D,A/T,NaN,417.0HP Electric Motor Electric Fuel System
3709,Ford,Mustang Mach-E Select,A/T,NaN,266.0HP Electric Motor Electric Fuel System
3739,Tesla,Model 3 Long Range,A/T,NaN,271.0HP Electric Motor Electric Fuel System
3764,Audi,Q4 e-tron 50 Premium Plus,1-Speed A/T,NaN,295.0HP Electric Motor Electric Fuel System
3768,GMC,HUMMER EV Edition 1,A/T,NaN,Electric Motor Electric Fuel System
3783,Porsche,Taycan 4S,2-Speed A/T,NaN,482.0HP Electric Motor Electric Fuel System
3813,Ford,Mustang Mach-E GT,A/T,NaN,480.0HP Electric Motor Electric Fuel System
3834,Ford,F-150 Lightning LARIAT,1-Speed A/T,NaN,563.0HP Electric Motor Electric Fuel System
3896,Tesla,Model Y Performance,A/T,NaN,455.0HP Electric Motor Electric Fuel System
3906,Tesla,Model 3 Long Range,1-Speed A/T,NaN,425.0HP Electric Motor Electric Fuel System
3913,Tesla,Model S 100D,A/T,NaN,518.0HP Electric Motor Electric Fuel System
3932,Tesla,Model X Performance,A/T,NaN,778.0HP Electric Motor Electric Fuel System

In [262]:
df['fuel_type']=(df['fuel_type'].where(
    ~df['engine']
    .str.contains('Electric Motor Electric Fuel System',case=False,na=False),
    df['fuel_type'].fillna('Electric')))

In [263]:
df.loc[
    df['engine']
    .str.contains('Electric Motor Electric Fuel System',case=False,na=False),
    ['brand','model','transmission','fuel_type','engine']
    ]

,brand,model,transmission,fuel_type,engine
9,Tesla,Model X Long Range Plus,A/T,Electric,534.0HP Electric Motor Electric Fuel System
44,Lucid,Air Grand Touring,1-Speed A/T,Electric,536.0HP Electric Motor Electric Fuel System
68,Lucid,Air Grand Touring,1-Speed A/T,Electric,536.0HP Electric Motor Electric Fuel System
92,Rivian,R1S Adventure Package,1-Speed A/T,Electric,835.0HP Electric Motor Electric Fuel System
122,Rivian,R1S Adventure Package,A/T,Electric,835.0HP Electric Motor Electric Fuel System
129,Lucid,Air Pure,A/T,Electric,620.0HP Electric Motor Electric Fuel System
155,Tesla,Model 3 Performance,A/T,Electric,455.0HP Electric Motor Electric Fuel System
189,Tesla,Model Y Performance,1-Speed A/T,Electric,455.0HP Electric Motor Electric Fuel System
225,Tesla,Model X Base,A/T,Electric,670.0HP Electric Motor Electric Fuel System
253,Mercedes-Benz,EQS 450 4MATIC,1-Speed A/T,Electric,355.0HP Electric Motor Electric Fuel System
266,Mercedes-Benz,EQS 450+ Base,1-Speed A/T,Electric,329.0HP Electric Motor Electric Fuel System
298,Tesla,Model 3 Standard Range Plus,A/T,Electric,271.0HP Electric Motor Electric Fuel System
346,Tesla,Model X Long Range,1-Speed A/T,Electric,670.0HP Electric Motor Electric Fuel System
397,Rivian,R1S Adventure Package,1-Speed A/T,Electric,835.0HP Electric Motor Electric Fuel System
410,Rivian,R1S Adventure Package,1-Speed A/T,Electric,835.0HP Electric Motor Electric Fuel System
451,Audi,e-tron Prestige,1-Speed A/T,Electric,355.0HP Electric Motor Electric Fuel System
472,Rivian,R1S Adventure Package,A/T,Electric,835.0HP Electric Motor Electric Fuel System
503,Chevrolet,Bolt EUV Premier,A/T,Electric,200.0HP Electric Motor Electric Fuel System
518,Tesla,Model Y Long Range,A/T,Electric,425.0HP Electric Motor Electric Fuel System
526,Rivian,R1S Adventure Package,A/T,Electric,835.0HP Electric Motor Electric Fuel System
529,Tesla,Model Y Long Range,1-Speed A/T,Electric,425.0HP Electric Motor Electric Fuel System
542,Nissan,Leaf S,A/T,Electric,147.0HP Electric Motor Electric Fuel System
543,Nissan,Leaf SL,1-Speed A/T,Electric,107.0HP Electric Motor Electric Fuel System
684,Audi,e-tron Prestige,A/T,Electric,355.0HP Electric Motor Electric Fuel System
687,Chevrolet,Bolt EUV Premier,1-Speed A/T,Electric,200.0HP Electric Motor Electric Fuel System
703,Tesla,Model Y Long Range,A/T,Electric,425.0HP Electric Motor Electric Fuel System
719,Karma,Revero Base,A/T,Electric,403.0HP 2.0L Electric Motor Electric Fuel System
721,Ford,Mustang Mach-E California Route 1,1-Speed A/T,Electric,290.0HP Electric Motor Electric Fuel System
746,Ford,Mustang Mach-E Premium,A/T,Electric,266.0HP Electric Motor Electric Fuel System
752,Ford,Mustang Mach-E Premium,1-Speed A/T,Electric,346.0HP Electric Motor Electric Fuel System
753,FIAT,500e Battery Electric,1-Speed A/T,Electric,111.0HP Electric Motor Electric Fuel System
757,Rivian,R1S Adventure Package,1-Speed A/T,Electric,835.0HP Electric Motor Electric Fuel System
799,Tesla,Model S 70D,A/T,Electric,329.0HP Electric Motor Electric Fuel System
943,Nissan,Leaf SV PLUS,1-Speed A/T,Electric,214.0HP Electric Motor Electric Fuel System
1008,Volvo,C40 Recharge Pure Electric Twin Ultimate,A/T,Electric,402.0HP Electric Motor Electric Fuel System
1047,Tesla,Model X Long Range Plus,1-Speed A/T,Electric,534.0HP Electric Motor Electric Fuel System
1071,Tesla,Model Y Long Range,A/T,Electric,425.0HP Electric Motor Electric Fuel System
1091,Tesla,Model X Base,A/T,Electric,670.0HP Electric Motor Electric Fuel System
1098,BMW,i3 Base w/Range Extender,1-Speed A/T,Electric,170.0HP 0.65L Electric Motor Electric Fuel System
1119,Hyundai,Kona EV SEL,1-Speed A/T,Electric,201.0HP Electric Motor Electric Fuel System
1126,Tesla,Model X P90D,A/T,Electric,691.0HP Electric Motor Electric Fuel System
1139,Kia,EV6 GT-Line,1-Speed A/T,Electric,320.0HP Electric Motor Electric Fuel System
1157,Tesla,Model Y Performance,1-Speed A/T,Electric,455.0HP Electric Motor Electric Fuel System
1203,Rivian,R1S Launch Edition,1-Speed A/T,Electric,835.0HP Electric Motor Electric Fuel System
1212,Tesla,Model Y Long Range,A/T,Electric,425.0HP Electric Motor Electric Fuel System
1230,Tesla,Model Y Long Range,A/T,Electric,425.0HP Electric Motor Electric Fuel System
1235,Nissan,Leaf SL,1-Speed A/T,Electric,107.0HP Electric Motor Electric Fuel System
1247,Tesla,Model Y Long Range,A/T,Electric,425.0HP Electric Motor Electric Fuel System
1250,Audi,Q4 e-tron Sportback Premium,A/T,Electric,295.0HP Electric Motor Electric Fuel System
1293,Tesla,Model 3 Standard Range Plus,A/T,Electric,Electric Motor Electric Fuel System
1330,Rivian,R1S Adventure Package,A/T,Electric,835.0HP Electric Motor Electric Fuel System
1331,Tesla,Model Y Long Range,A/T,Electric,425.0HP Electric Motor Electric Fuel System
1509,Hyundai,IONIQ 5 SE,A/T,Electric,320.0HP Electric Motor Electric Fuel System
1522,Ford,F-150 Lightning XLT,A/T,Electric,563.0HP Electric Motor Electric Fuel System
1534,Tesla,Model X 75D,A/T,Electric,518.0HP Electric Motor Electric Fuel System
1544,Rivian,R1S Launch Edition,1-Speed A/T,Electric,835.0HP Electric Motor Electric Fuel System
1554,Karma,Revero Base,A/T,Electric,403.0HP 2.0L Electric Motor Electric Fuel System
1593,Tesla,Model S P100D,A/T,Electric,518.0HP Electric Motor Electric Fuel System
1598,Tesla,Model X Long Range Plus,A/T,Electric,557.0HP Electric Motor Electric Fuel System
1697,Cadillac,LYRIQ Luxury,A/T,Electric,500.0HP Electric Motor Electric Fuel System
1709,Tesla,Model S P100D,A/T,Electric,518.0HP Electric Motor Electric Fuel System
1788,Tesla,Model S 85D,1-Speed A/T,Electric,422.0HP Electric Motor Electric Fuel System
1836,Rivian,R1S Adventure Package,A/T,Electric,835.0HP Electric Motor Electric Fuel System
1884,Tesla,Model 3 Performance,1-Speed A/T,Electric,271.0HP Electric Motor Electric Fuel System
1888,Tesla,Model S 100D,A/T,Electric,518.0HP Electric Motor Electric Fuel System
1901,Tesla,Model S Performance,1-Speed A/T,Electric,778.0HP Electric Motor Electric Fuel System
1911,Porsche,Taycan Turbo,A/T,Electric,616.0HP Electric Motor Electric Fuel System
1943,Tesla,Model 3 Standard Range Plus,A/T,Electric,Electric Motor Electric Fuel System
2066,Chevrolet,Bolt EV LT,A/T,Electric,200.0HP Electric Motor Electric Fuel System
2102,Tesla,Model 3 Long Range,A/T,Electric,271.0HP Electric Motor Electric Fuel System
2116,Tesla,Model S P100D,1-Speed A/T,Electric,Electric Motor Electric Fuel System
2124,Tesla,Model X Long Range,1-Speed A/T,Electric,518.0HP Electric Motor Electric Fuel System
2181,Tesla,Model 3 Base,A/T,Electric,271.0HP Electric Motor Electric Fuel System
2184,Rivian,R1S Adventure Package,1-Speed A/T,Electric,835.0HP Electric Motor Electric Fuel System
2191,Tesla,Model 3 Performance,1-Speed A/T,Electric,455.0HP Electric Motor Electric Fuel System
2209,Tesla,Model 3 Standard Range Plus,A/T,Electric,Electric Motor Electric Fuel System
2231,Tesla,Model 3 Long Range,A/T,Electric,Electric Motor Electric Fuel System
2233,Rivian,R1T Launch Edition,A/T,Electric,835.0HP Electric Motor Electric Fuel System
2236,Tesla,Model 3 Mid Range,A/T,Electric,271.0HP Electric Motor Electric Fuel System
2250,Tesla,Model 3 Long Range,A/T,Electric,425.0HP Electric Motor Electric Fuel System
2322,Tesla,Model Y Performance,A/T,Electric,455.0HP Electric Motor Electric Fuel System
2343,Tesla,Model 3 Long Range,1-Speed A/T,Electric,271.0HP Electric Motor Electric Fuel System
2345,Tesla,Model Y Long Range,A/T,Electric,425.0HP Electric Motor Electric Fuel System
2407,Rivian,R1S Adventure Package,A/T,Electric,533.0HP Electric Motor Electric Fuel System
2426,Volkswagen,ID.4 Pro S,1-Speed A/T,Electric,295.0HP Electric Motor Electric Fuel System
2451,Tesla,Model S Long Range,1-Speed A/T,Electric,670.0HP Electric Motor Electric Fuel System
2472,Rivian,R1S Launch Edition,1-Speed A/T,Electric,835.0HP Electric Motor Electric Fuel System
2484,Tesla,Model Y Performance,A/T,Electric,455.0HP Electric Motor Electric Fuel System
2492,Tesla,Model Y Performance,1-Speed A/T,Electric,455.0HP Electric Motor Electric Fuel System
2677,Rivian,R1S Adventure Package,A/T,Electric,835.0HP Electric Motor Electric Fuel System
2770,Kia,Niro EV EX,1-Speed A/T,Electric,201.0HP Electric Motor Electric Fuel System
2772,Porsche,Taycan Base,2-Speed A/T,Electric,321.0HP Electric Motor Electric Fuel System
2779,Tesla,Model S Performance,A/T,Electric,416.0HP Electric Motor Electric Fuel System
2795,Mercedes-Benz,EQS 450+ Base,A/T,Electric,329.0HP Electric Motor Electric Fuel System
2870,Tesla,Model Y Performance,A/T,Electric,455.0HP Electric Motor Electric Fuel System
2877,Tesla,Model X P100D,1-Speed A/T,Electric,Electric Motor Electric Fuel System
2952,Ford,Mustang Mach-E Premium,1-Speed A/T,Electric,346.0HP Electric Motor Electric Fuel System
2956,Tesla,Model Y Long Range,A/T,Electric,425.0HP Electric Motor Electric Fuel System
2964,Hyundai,Kona EV SEL,1-Speed A/T,Electric,201.0HP Electric Motor Electric Fuel System
2979,Tesla,Model Y Performance,A/T,Electric,455.0HP Electric Motor Electric Fuel System
2982,Tesla,Model S 85,A/T,Electric,362.0HP Electric Motor Electric Fuel System
2984,Tesla,Model 3 Standard Range,A/T,Electric,271.0HP Electric Motor Electric Fuel System
3033,Porsche,Taycan Base,A/T,Electric,375.0HP Electric Motor Electric Fuel System
3048,Tesla,Model Y Performance,1-Speed A/T,Electric,455.0HP Electric Motor Electric Fuel System
3061,Tesla,Model 3 Long Range,A/T,Electric,Electric Motor Electric Fuel System
3090,BMW,i3 120Ah w/Range Extender,A/T,Electric,170.0HP 0.65L Electric Motor Electric Fuel System
3109,Tesla,Model Y Long Range,A/T,Electric,425.0HP Electric Motor Electric Fuel System
3128,Tesla,Model S 100D,1-Speed A/T,Electric,Electric Motor Electric Fuel System
3134,Tesla,Model X 75D,A/T,Electric,518.0HP Electric Motor Electric Fuel System
3151,Tesla,Model S Long Range Plus,A/T,Electric,557.0HP Electric Motor Electric Fuel System
3164,Tesla,Model Y Long Range,1-Speed A/T,Electric,425.0HP Electric Motor Electric Fuel System
3168,Volkswagen,e-Golf SE,1-Speed A/T,Electric,115.0HP Electric Motor Electric Fuel System
3169,Tesla,Model X Long Range,A/T,Electric,670.0HP Electric Motor Electric Fuel System
3193,Tesla,Model X 75D,A/T,Electric,518.0HP Electric Motor Electric Fuel System
3196,Tesla,Model X Long Range,A/T,Electric,670.0HP Electric Motor Electric Fuel System
3207,Kia,EV6 GT-Line,1-Speed A/T,Electric,320.0HP Electric Motor Electric Fuel System
3224,Ford,Mustang Mach-E GT,1-Speed A/T,Electric,480.0HP Electric Motor Electric Fuel System
3255,BMW,i3 Base,1-Speed A/T,Electric,170.0HP 0.65L Electric Motor Electric Fuel System
3272,Tesla,Model S Long Range,1-Speed A/T,Electric,670.0HP Electric Motor Electric Fuel System
3314,Tesla,Model S 75D,1-Speed A/T,Electric,518.0HP Electric Motor Electric Fuel System
3324,BMW,i3 Base w/Range Extender,A/T,Electric,170.0HP 0.65L Electric Motor Electric Fuel System
3383,Tesla,Model 3 Performance,1-Speed A/T,Electric,455.0HP Electric Motor Electric Fuel System
3399,Tesla,Model X 100D,1-Speed A/T,Electric,518.0HP Electric Motor Electric Fuel System
3417,Porsche,Taycan Base,2-Speed A/T,Electric,375.0HP Electric Motor Electric Fuel System
3425,Tesla,Model X Plaid,A/T,Electric,1020.0HP Electric Motor Electric Fuel System
3427,Tesla,Model S 100D,1-Speed A/T,Electric,518.0HP Electric Motor Electric Fuel System
3468,BMW,i3 94 Ah,1-Speed A/T,Electric,170.0HP 0.65L Electric Motor Electric Fuel System
3502,Ford,Mustang Mach-E GT,1-Speed A/T,Electric,480.0HP Electric Motor Electric Fuel System
3510,Tesla,Model S Plaid,A/T,Electric,1020.0HP Electric Motor Electric Fuel System
3520,Chevrolet,Bolt EV LT,1-Speed A/T,Electric,200.0HP Electric Motor Electric Fuel System
3557,Rivian,R1S Launch Edition,1-Speed A/T,Electric,835.0HP Electric Motor Electric Fuel System
3618,Tesla,Model 3 Long Range,1-Speed A/T,Electric,271.0HP Electric Motor Electric Fuel System
3647,Tesla,Model Y Long Range,1-Speed A/T,Electric,425.0HP Electric Motor Electric Fuel System
3673,Tesla,Model Y Long Range,1-Speed A/T,Electric,425.0HP Electric Motor Electric Fuel System
3682,Tesla,Model S 90D,A/T,Electric,417.0HP Electric Motor Electric Fuel System
3709,Ford,Mustang Mach-E Select,A/T,Electric,266.0HP Electric Motor Electric Fuel System
3739,Tesla,Model 3 Long Range,A/T,Electric,271.0HP Electric Motor Electric Fuel System
3764,Audi,Q4 e-tron 50 Premium Plus,1-Speed A/T,Electric,295.0HP Electric Motor Electric Fuel System
3768,GMC,HUMMER EV Edition 1,A/T,Electric,Electric Motor Electric Fuel System
3783,Porsche,Taycan 4S,2-Speed A/T,Electric,482.0HP Electric Motor Electric Fuel System
3813,Ford,Mustang Mach-E GT,A/T,Electric,480.0HP Electric Motor Electric Fuel System
3834,Ford,F-150 Lightning LARIAT,1-Speed A/T,Electric,563.0HP Electric Motor Electric Fuel System
3896,Tesla,Model Y Performance,A/T,Electric,455.0HP Electric Motor Electric Fuel System
3906,Tesla,Model 3 Long Range,1-Speed A/T,Electric,425.0HP Electric Motor Electric Fuel System
3913,Tesla,Model S 100D,A/T,Electric,518.0HP Electric Motor Electric Fuel System
3932,Tesla,Model X Performance,A/T,Electric,778.0HP Electric Motor Electric Fuel System

In [264]:
missing_info={}
for col in Categorical_Columns:
    if df[col].isnull().sum()>0:
        missing_count=(df[col].isnull().sum()/len(df))*100
        missing_info[col]=round(missing_count,2)
print("\n The Categorical columns with missing percentage is:\n")
for col,per in missing_info.items():
    print(f"{col}: {per}%")

 The Categorical columns with missing percentage is:

fuel_type: 0.6%
accident: 2.82%

In [265]:
df[df['fuel_type'].isna()]

,brand,model,model_year,milage,fuel_type,engine,transmission,ext_col,int_col,accident,clean_title,price,Accident_Occurred,Engine_Capacity,Horse_Power
236,Polestar,2 Launch Edition,2021,12172.0,NaN,Electric,1-Speed Automatic,Thunder Gray,Charcoal,None reported,Unknown,35999.0,NO,NaN,NaN
321,Chevrolet,Bolt EUV Premier,2022,7624.0,NaN,Electric,1-Speed Automatic,Mosaic Black Metallic,Jet Black,None reported,Yes,31985.0,NO,NaN,NaN
383,Ford,Mustang Mach-E Select,2023,923.0,NaN,Standard Range Battery,Automatic,Rapid Red Metallic Tinted Clearcoat,Black Onyx,None reported,Unknown,46998.0,NO,NaN,NaN
456,Kia,EV6 Wind,2022,11945.0,NaN,111.2Ah / FR 70kW / RR 160kW (697V),Automatic,Glacier,Black,None reported,Unknown,38998.0,NO,NaN,NaN
555,Tesla,Model 3 Long Range,2022,3077.0,NaN,Dual Motor - Standard,Automatic,Silver,Black,None reported,Unknown,44998.0,NO,NaN,NaN
962,Audi,e-tron Prestige,2019,7874.0,NaN,Electric,1-Speed Automatic,Typhoon Gray Metallic,Pearl Beige,None reported,Unknown,38999.0,NO,NaN,NaN
981,Audi,e-tron Premium,2021,18031.0,NaN,Electric,1-Speed Automatic,Navarra Blue Metallic,Black,None reported,Unknown,39599.0,NO,NaN,NaN
1007,Tesla,Model Y Performance,2020,30554.0,NaN,Electric,1-Speed Automatic,Blue,Black,None reported,Unknown,41999.0,NO,NaN,NaN
1221,Toyota,bZ4X Limited,2023,6548.0,NaN,Electric,Automatic,Wind Chill Pearl,Black,None reported,Unknown,41999.0,NO,NaN,NaN
1228,Tesla,Model X Performance,2020,27224.0,NaN,Electric,1-Speed Automatic,Black,Black,None reported,Unknown,65999.0,NO,NaN,NaN
1241,Porsche,Taycan Turbo,2020,21028.0,NaN,Dual AC Electric Motors,Single-Speed Fixed Gear,BLACK,BEIGE,None reported,Unknown,96900.0,NO,NaN,NaN
1316,Porsche,Taycan Base,2021,6785.0,NaN,Electric,2-Speed Automatic,Gentian Blue Metallic,Black,None reported,Unknown,108900.0,NO,NaN,NaN
1542,Nissan,Leaf SV PLUS,2023,5121.0,NaN,Electric,1-Speed Automatic,Brilliant Silver Metallic,Black,None reported,Yes,28196.0,NO,NaN,NaN
1651,Ford,Mustang Mach-E GT,2022,7661.0,NaN,Electric,1-Speed Automatic,Star White,Black Onyx,None reported,Unknown,49599.0,NO,NaN,NaN
1800,Tesla,Model Y Long Range,2022,4665.0,NaN,Dual Motor - Standard,Automatic,Silver,Black,None reported,Unknown,46598.0,NO,NaN,NaN
1954,Tesla,Model 3,2018,26609.0,NaN,Electric,Automatic,Gray,–,None reported,Unknown,36998.0,NO,NaN,NaN
2379,Tesla,Model S P100D,2018,10065.0,NaN,Electric,1-Speed Automatic,Red Multi,White,None reported,Unknown,59999.0,NO,NaN,NaN
2613,Tesla,Model Y Long Range,2022,9411.0,NaN,Dual Motor - Standard,Automatic,Silver,Black,None reported,Unknown,47998.0,NO,NaN,NaN
3466,Tesla,Model 3 Long Range,2022,22457.0,NaN,Electric,Automatic,Midnight Silver Metallic,Black,None reported,Unknown,40036.0,NO,NaN,NaN
3470,Porsche,Taycan Turbo,2020,2076.0,NaN,Electric,Automatic,Gray,Red,None reported,Unknown,115998.0,NO,NaN,NaN
3649,Volkswagen,ID.4 Pro S,2023,1716.0,NaN,Battery Electric,Automatic,Gray,Gray w/Blue Bolsters,None reported,Unknown,39998.0,NO,NaN,NaN
3908,Tesla,Model Y Long Range,2021,49252.0,NaN,Electric,1-Speed Automatic,Deep Blue Metallic,Black,None reported,Unknown,37999.0,NO,NaN,NaN
3961,Tesla,Model 3 Long Range,2021,23749.0,NaN,Electric,1-Speed Automatic,White,Black,None reported,Unknown,35999.0,NO,NaN,NaN
4006,Porsche,Taycan,2022,2116.0,NaN,Electric,Automatic,Black,Black,None reported,Unknown,90998.0,NO,NaN,NaN

In [266]:
df.loc[
    df['engine']
    .str.contains('Electric',case=False,na=False),
    ['brand','model','transmission','fuel_type','engine']
    ]

,brand,model,transmission,fuel_type,engine
3,INFINITI,Q50 Hybrid Sport,7-Speed A/T,Hybrid,354.0HP 3.5L V6 Cylinder Engine Gas/Electric Hybrid
9,Tesla,Model X Long Range Plus,A/T,Electric,534.0HP Electric Motor Electric Fuel System
44,Lucid,Air Grand Touring,1-Speed A/T,Electric,536.0HP Electric Motor Electric Fuel System
60,Volvo,XC90 Hybrid T8 R-Design,Transmission w/Dual Shift Mode,Plug-In Hybrid,400.0HP 2.0L 4 Cylinder Engine Plug-In Electric/Gas
65,BMW,X4 M40i,Transmission w/Dual Shift Mode,Hybrid,382.0HP 3.0L Straight 6 Cylinder Engine Gasoline/Mild Electric Hybrid
68,Lucid,Air Grand Touring,1-Speed A/T,Electric,536.0HP Electric Motor Electric Fuel System
84,Hyundai,Sonata Hybrid Limited,A/T,Hybrid,199.0HP 2.4L 4 Cylinder Engine Gas/Electric Hybrid
87,Mercedes-Benz,GLS 450 Base 4MATIC,9-Speed A/T,Hybrid,362.0HP 3.0L Straight 6 Cylinder Engine Gasoline/Mild Electric Hybrid
92,Rivian,R1S Adventure Package,1-Speed A/T,Electric,835.0HP Electric Motor Electric Fuel System
103,BMW,i8 Base,Transmission w/Dual Shift Mode,Plug-In Hybrid,369.0HP 1.5L 3 Cylinder Engine Plug-In Electric/Gas
104,Lexus,ES 300h Base,CVT Transmission,Hybrid,200.0HP 2.5L 4 Cylinder Engine Gas/Electric Hybrid
122,Rivian,R1S Adventure Package,A/T,Electric,835.0HP Electric Motor Electric Fuel System
124,Porsche,Cayenne E-Hybrid S,Transmission w/Dual Shift Mode,Plug-In Hybrid,416.0HP 3.0L V6 Cylinder Engine Plug-In Electric/Gas
126,INFINITI,Q70h Base,7-Speed A/T,Hybrid,360.0HP 3.5L V6 Cylinder Engine Gas/Electric Hybrid
129,Lucid,Air Pure,A/T,Electric,620.0HP Electric Motor Electric Fuel System
155,Tesla,Model 3 Performance,A/T,Electric,455.0HP Electric Motor Electric Fuel System
178,Lincoln,MKZ Hybrid Base,A/T,Hybrid,188.0HP 2.0L 4 Cylinder Engine Gas/Electric Hybrid
189,Tesla,Model Y Performance,1-Speed A/T,Electric,455.0HP Electric Motor Electric Fuel System
225,Tesla,Model X Base,A/T,Electric,670.0HP Electric Motor Electric Fuel System
236,Polestar,2 Launch Edition,1-Speed Automatic,NaN,Electric
239,Lincoln,Corsair Grand Touring,CVT Transmission,Plug-In Hybrid,266.0HP 2.5L 4 Cylinder Engine Plug-In Electric/Gas
253,Mercedes-Benz,EQS 450 4MATIC,1-Speed A/T,Electric,355.0HP Electric Motor Electric Fuel System
266,Mercedes-Benz,EQS 450+ Base,1-Speed A/T,Electric,329.0HP Electric Motor Electric Fuel System
279,Audi,S7 2.9T Prestige,8-Speed A/T,Hybrid,444.0HP 2.9L V6 Cylinder Engine Gasoline/Mild Electric Hybrid
293,BMW,i8 Base,A/T,Plug-In Hybrid,357.0HP 1.5L 3 Cylinder Engine Plug-In Electric/Gas
298,Tesla,Model 3 Standard Range Plus,A/T,Electric,271.0HP Electric Motor Electric Fuel System
306,Mercedes-Benz,AMG GLS 63 4MATIC,9-Speed A/T,Hybrid,603.0HP 4.0L 8 Cylinder Engine Gasoline/Mild Electric Hybrid
321,Chevrolet,Bolt EUV Premier,1-Speed Automatic,NaN,Electric
346,Tesla,Model X Long Range,1-Speed A/T,Electric,670.0HP Electric Motor Electric Fuel System
361,Toyota,Tundra Hybrid TRD Pro,10-Speed A/T,Hybrid,437.0HP 3.4L V6 Cylinder Engine Gas/Electric Hybrid
379,Ford,Fusion Energi Titanium,CVT Transmission,Plug-In Hybrid,188.0HP 2.0L 4 Cylinder Engine Plug-In Electric/Gas
380,Toyota,Tundra Hybrid TRD Pro,10-Speed A/T,Hybrid,437.0HP 3.4L V6 Cylinder Engine Gas/Electric Hybrid
397,Rivian,R1S Adventure Package,1-Speed A/T,Electric,835.0HP Electric Motor Electric Fuel System
403,BMW,X7 xDrive40i,Transmission w/Dual Shift Mode,Hybrid,375.0HP 3.0L Straight 6 Cylinder Engine Gasoline/Mild Electric Hybrid
410,Rivian,R1S Adventure Package,1-Speed A/T,Electric,835.0HP Electric Motor Electric Fuel System
411,Toyota,RAV4 Hybrid XLE,CVT Transmission,Hybrid,219.0HP 2.5L 4 Cylinder Engine Gas/Electric Hybrid
435,Mercedes-Benz,S-Class S 580 4MATIC,9-Speed A/T,Hybrid,496.0HP 4.0L 8 Cylinder Engine Gasoline/Mild Electric Hybrid
451,Audi,e-tron Prestige,1-Speed A/T,Electric,355.0HP Electric Motor Electric Fuel System
472,Rivian,R1S Adventure Package,A/T,Electric,835.0HP Electric Motor Electric Fuel System
499,Toyota,Highlander Hybrid Limited,A/T,Hybrid,208.0HP 3.3L V6 Cylinder Engine Gas/Electric Hybrid
503,Chevrolet,Bolt EUV Premier,A/T,Electric,200.0HP Electric Motor Electric Fuel System
505,BMW,X7 xDrive40i,8-Speed A/T,Hybrid,375.0HP 3.0L Straight 6 Cylinder Engine Gasoline/Mild Electric Hybrid
514,Volvo,XC90 Hybrid T8 Inscription,8-Speed A/T,Plug-In Hybrid,400.0HP 2.0L 4 Cylinder Engine Plug-In Electric/Gas
518,Tesla,Model Y Long Range,A/T,Electric,425.0HP Electric Motor Electric Fuel System
526,Rivian,R1S Adventure Package,A/T,Electric,835.0HP Electric Motor Electric Fuel System
529,Tesla,Model Y Long Range,1-Speed A/T,Electric,425.0HP Electric Motor Electric Fuel System
542,Nissan,Leaf S,A/T,Electric,147.0HP Electric Motor Electric Fuel System
543,Nissan,Leaf SL,1-Speed A/T,Electric,107.0HP Electric Motor Electric Fuel System
557,Ford,C-Max Energi SE,CVT Transmission,Plug-In Hybrid,188.0HP 2.0L 4 Cylinder Engine Plug-In Electric/Gas
575,BMW,330e iPerformance,Transmission w/Dual Shift Mode,Plug-In Hybrid,247.0HP 2.0L 4 Cylinder Engine Plug-In Electric/Gas
581,Hyundai,IONIQ Plug-In Hybrid SEL,A/T,Plug-In Hybrid,139.0HP 1.6L 4 Cylinder Engine Plug-In Electric/Gas
583,BMW,X5 PHEV xDrive45e,8-Speed A/T,Plug-In Hybrid,389.0HP 3.0L Straight 6 Cylinder Engine Plug-In Electric/Gas
638,Audi,A7 55 Premium Plus,A/T,Hybrid,335.0HP 3.0L V6 Cylinder Engine Gasoline/Mild Electric Hybrid
649,BMW,i8 Base,6-Speed A/T,Plug-In Hybrid,369.0HP 1.5L 3 Cylinder Engine Plug-In Electric/Gas
650,Lexus,CT 200h Premium,A/T,Hybrid,134.0HP 1.8L 4 Cylinder Engine Gas/Electric Hybrid
675,Kia,Optima Hybrid LX,A/T,Hybrid,199.0HP 2.4L 4 Cylinder Engine Gas/Electric Hybrid
684,Audi,e-tron Prestige,A/T,Electric,355.0HP Electric Motor Electric Fuel System
687,Chevrolet,Bolt EUV Premier,1-Speed A/T,Electric,200.0HP Electric Motor Electric Fuel System
702,BMW,330e iPerformance,Transmission w/Dual Shift Mode,Plug-In Hybrid,247.0HP 2.0L 4 Cylinder Engine Plug-In Electric/Gas
703,Tesla,Model Y Long Range,A/T,Electric,425.0HP Electric Motor Electric Fuel System
712,Maserati,Grecale Modena,Transmission w/Dual Shift Mode,Hybrid,325.0HP 2.0L 4 Cylinder Engine Gasoline/Mild Electric Hybrid
713,Lexus,RX 450h Base,CVT Transmission,Hybrid,308.0HP 3.5L V6 Cylinder Engine Gas/Electric Hybrid
717,Hyundai,Tucson Hybrid SEL Convenience,A/T,Hybrid,226.0HP 1.6L 4 Cylinder Engine Gas/Electric Hybrid
719,Karma,Revero Base,A/T,Electric,403.0HP 2.0L Electric Motor Electric Fuel System
721,Ford,Mustang Mach-E California Route 1,1-Speed A/T,Electric,290.0HP Electric Motor Electric Fuel System
745,Kia,Sportage Plug-In Hybrid X-Line,A/T,Plug-In Hybrid,177.0HP 1.6L 4 Cylinder Engine Plug-In Electric/Gas
746,Ford,Mustang Mach-E Premium,A/T,Electric,266.0HP Electric Motor Electric Fuel System
748,Jeep,Wrangler Rubicon,8-Speed A/T,Hybrid,285.0HP 3.6L V6 Cylinder Engine Gasoline/Mild Electric Hybrid
752,Ford,Mustang Mach-E Premium,1-Speed A/T,Electric,346.0HP Electric Motor Electric Fuel System
753,FIAT,500e Battery Electric,1-Speed A/T,Electric,111.0HP Electric Motor Electric Fuel System
757,Rivian,R1S Adventure Package,1-Speed A/T,Electric,835.0HP Electric Motor Electric Fuel System
780,BMW,M440 i,8-Speed A/T,Hybrid,382.0HP 3.0L Straight 6 Cylinder Engine Gasoline/Mild Electric Hybrid
781,Audi,A8 L 55,A/T,Hybrid,335.0HP 3.0L V6 Cylinder Engine Gasoline/Mild Electric Hybrid
799,Tesla,Model S 70D,A/T,Electric,329.0HP Electric Motor Electric Fuel System
801,Hyundai,Sonata Hybrid Limited,A/T,Hybrid,192.0HP 2.0L 4 Cylinder Engine Gas/Electric Hybrid
804,INFINITI,Q50 Hybrid Premium,7-Speed A/T,Hybrid,354.0HP 3.5L V6 Cylinder Engine Gas/Electric Hybrid
821,Audi,A8 L 55,8-Speed A/T,Hybrid,335.0HP 3.0L V6 Cylinder Engine Gasoline/Mild Electric Hybrid
847,BMW,M440 i xDrive,8-Speed A/T,Hybrid,382.0HP 3.0L Straight 6 Cylinder Engine Gasoline/Mild Electric Hybrid
867,BMW,X5 eDrive xDrive40e,8-Speed A/T,Plug-In Hybrid,313.0HP 2.0L 4 Cylinder Engine Plug-In Electric/Gas
874,BMW,M340 i xDrive,8-Speed A/T,Hybrid,382.0HP 3.0L Straight 6 Cylinder Engine Gasoline/Mild Electric Hybrid
880,Toyota,Highlander Hybrid XLE,A/T,Hybrid,306.0HP 3.5L V6 Cylinder Engine Gas/Electric Hybrid
894,Toyota,Camry Hybrid Base,A/T,Hybrid,147.0HP 2.4L 4 Cylinder Engine Gas/Electric Hybrid
943,Nissan,Leaf SV PLUS,1-Speed A/T,Electric,214.0HP Electric Motor Electric Fuel System
949,Audi,A7 55 Premium,A/T,Hybrid,335.0HP 3.0L V6 Cylinder Engine Gasoline/Mild Electric Hybrid
952,Land,Rover Range Rover HSE SWB,A/T,Hybrid,395.0HP 3.0L Straight 6 Cylinder Engine Gasoline/Mild Electric Hybrid
962,Audi,e-tron Prestige,1-Speed Automatic,NaN,Electric
981,Audi,e-tron Premium,1-Speed Automatic,NaN,Electric
982,Toyota,Sequoia Limited,10-Speed A/T,Hybrid,437.0HP 3.4L V6 Cylinder Engine Gas/Electric Hybrid
983,Land,Rover Range Rover Sport HST MHEV,Transmission w/Dual Shift Mode,Hybrid,395.0HP 3.0L Straight 6 Cylinder Engine Gasoline/Mild Electric Hybrid
997,Audi,Q8 55 Premium Plus,Transmission w/Dual Shift Mode,Hybrid,335.0HP 3.0L V6 Cylinder Engine Gasoline/Mild Electric Hybrid
1005,Land,Rover Defender SE,A/T,Hybrid,395.0HP 3.0L Straight 6 Cylinder Engine Gasoline/Mild Electric Hybrid
1007,Tesla,Model Y Performance,1-Speed Automatic,NaN,Electric
1008,Volvo,C40 Recharge Pure Electric Twin Ultimate,A/T,Electric,402.0HP Electric Motor Electric Fuel System
1021,Toyota,Camry Hybrid LE,CVT Transmission,Hybrid,208.0HP 2.5L 4 Cylinder Engine Gas/Electric Hybrid
1023,Lexus,RX 450h Base,A/T,Hybrid,295.0HP 3.5L V6 Cylinder Engine Gas/Electric Hybrid
1047,Tesla,Model X Long Range Plus,1-Speed A/T,Electric,534.0HP Electric Motor Electric Fuel System
1057,BMW,X6 xDrive40i,Transmission w/Dual Shift Mode,Hybrid,335.0HP 3.0L Straight 6 Cylinder Engine Gasoline/Mild Electric Hybrid
1058,Land,Rover Range Rover P400 SE SWB,Transmission w/Dual Shift Mode,Hybrid,395.0HP 3.0L Straight 6 Cylinder Engine Gasoline/Mild Electric Hybrid
1069,Lexus,RX 450h Base,A/T,Hybrid,308.0HP 3.5L V6 Cylinder Engine Gas/Electric Hybrid
1071,Tesla,Model Y Long Range,A/T,Electric,425.0HP Electric Motor Electric Fuel System
1091,Tesla,Model X Base,A/T,Electric,670.0HP Electric Motor Electric Fuel System
1098,BMW,i3 Base w/Range Extender,1-Speed A/T,Electric,170.0HP 0.65L Electric Motor Electric Fuel System
1103,Mercedes-Benz,AMG E 53 Base 4MATIC,9-Speed A/T,Hybrid,429.0HP 3.0L Straight 6 Cylinder Engine Gasoline/Mild Electric Hybrid
1119,Hyundai,Kona EV SEL,1-Speed A/T,Electric,201.0HP Electric Motor Electric Fuel System
1126,Tesla,Model X P90D,A/T,Electric,691.0HP Electric Motor Electric Fuel System
1129,Audi,RS 7 4.0T,8-Speed A/T,Hybrid,591.0HP 4.0L 8 Cylinder Engine Gasoline/Mild Electric Hybrid
1139,Kia,EV6 GT-Line,1-Speed A/T,Electric,320.0HP Electric Motor Electric Fuel System
1155,Honda,Insight EX,CVT Transmission,Hybrid,151.0HP 1.5L 4 Cylinder Engine Gas/Electric Hybrid
1157,Tesla,Model Y Performance,1-Speed A/T,Electric,455.0HP Electric Motor Electric Fuel System
1203,Rivian,R1S Launch Edition,1-Speed A/T,Electric,835.0HP Electric Motor Electric Fuel System
1212,Tesla,Model Y Long Range,A/T,Electric,425.0HP Electric Motor Electric Fuel System
1221,Toyota,bZ4X Limited,Automatic,NaN,Electric
1228,Tesla,Model X Performance,1-Speed Automatic,NaN,Electric
1230,Tesla,Model Y Long Range,A/T,Electric,425.0HP Electric Motor Electric Fuel System
1235,Nissan,Leaf SL,1-Speed A/T,Electric,107.0HP Electric Motor Electric Fuel System
1241,Porsche,Taycan Turbo,Single-Speed Fixed Gear,NaN,Dual AC Electric Motors
1247,Tesla,Model Y Long Range,A/T,Electric,425.0HP Electric Motor Electric Fuel System
1250,Audi,Q4 e-tron Sportback Premium,A/T,Electric,295.0HP Electric Motor Electric Fuel System
1280,Kia,Optima Hybrid EX,A/T,Hybrid,206.0HP 2.4L 4 Cylinder Engine Gas/Electric Hybrid
1290,Hyundai,Sonata Hybrid Base,A/T,Hybrid,206.0HP 2.4L 4 Cylinder Engine Gas/Electric Hybrid
1293,Tesla,Model 3 Standard Range Plus,A/T,Electric,Electric Motor Electric Fuel System
1316,Porsche,Taycan Base,2-Speed Automatic,NaN,Electric
1319,Toyota,Camry Hybrid XLE,A/T,Hybrid,200.0HP 2.5L 4 Cylinder Engine Gas/Electric Hybrid
1324,BMW,M340 i xDrive,8-Speed A/T,Hybrid,382.0HP 3.0L Straight 6 Cylinder Engine Gasoline/Mild Electric Hybrid
1330,Rivian,R1S Adventure Package,A/T,Electric,835.0HP Electric Motor Electric Fuel System
1331,Tesla,Model Y Long Range,A/T,Electric,425.0HP Electric Motor Electric Fuel System
1333,BMW,X7 xDrive40i,8-Speed A/T,Hybrid,375.0HP 3.0L Straight 6 Cylinder Engine Gasoline/Mild Electric Hybrid
1346,Volvo,XC60 Recharge Plug-In Hybrid T8 Inscription,8-Speed A/T,Plug-In Hybrid,455.0HP 2.0L 4 Cylinder Engine Plug-In Electric/Gas
1353,Toyota,Sequoia Platinum,10-Speed A/T,Hybrid,437.0HP 3.4L V6 Cylinder Engine Gas/Electric Hybrid
1365,Mercedes-Benz,S-Class S 580 4MATIC,9-Speed A/T,Hybrid,496.0HP 4.0L 8 Cylinder Engine Gasoline/Mild Electric Hybrid
1368,Ford,Maverick Lariat,CVT Transmission,Hybrid,191.0HP 2.5L 4 Cylinder Engine Gas/Electric Hybrid
1373,Toyota,Corolla Hybrid LE,A/T,Hybrid,121.0HP 1.8L 4 Cylinder Engine Gas/Electric Hybrid
1394,BMW,X6 xDrive40i,A/T,Hybrid,335.0HP 3.0L Straight 6 Cylinder Engine Gasoline/Mild Electric Hybrid
1408,BMW,530e Base,A/T,Plug-In Hybrid,288.0HP 2.0L 4 Cylinder Engine Plug-In Electric/Gas
1428,Audi,Q8 3.0T Prestige,A/T,Hybrid,335.0HP 3.0L V6 Cylinder Engine Gasoline/Mild Electric Hybrid
1457,Mercedes-Benz,AMG GT 53 Base,9-Speed A/T,Hybrid,429.0HP 3.0L Straight 6 Cylinder Engine Gasoline/Mild Electric Hybrid
1509,Hyundai,IONIQ 5 SE,A/T,Electric,320.0HP Electric Motor Electric Fuel System
1522,Ford,F-150 Lightning XLT,A/T,Electric,563.0HP Electric Motor Electric Fuel System
1524,BMW,330e iPerformance,Transmission w/Dual Shift Mode,Plug-In Hybrid,247.0HP 2.0L 4 Cylinder Engine Plug-In Electric/Gas
1534,Tesla,Model X 75D,A/T,Electric,518.0HP Electric Motor Electric Fuel System
1542,Nissan,Leaf SV PLUS,1-Speed Automatic,NaN,Electric
1544,Rivian,R1S Launch Edition,1-Speed A/T,Electric,835.0HP Electric Motor Electric Fuel System
1545,Lexus,RX 450h Base,CVT Transmission,Hybrid,308.0HP 3.5L V6 Cylinder Engine Gas/Electric Hybrid
1554,Karma,Revero Base,A/T,Electric,403.0HP 2.0L Electric Motor Electric Fuel System
1572,BMW,X7 xDrive40i,A/T,Hybrid,335.0HP 3.0L Straight 6 Cylinder Engine Gasoline/Mild Electric Hybrid
1580,Toyota,Prius Touring,A/T,Hybrid,76.0HP 1.5L 4 Cylinder Engine Gas/Electric Hybrid
1593,Tesla,Model S P100D,A/T,Electric,518.0HP Electric Motor Electric Fuel System
1598,Tesla,Model X Long Range Plus,A/T,Electric,557.0HP Electric Motor Electric Fuel System
1599,Land,Rover Range Rover P400 SE SWB,A/T,Hybrid,395.0HP 3.0L Straight 6 Cylinder Engine Gasoline/Mild Electric Hybrid
1622,Toyota,Sequoia TRD Pro,10-Speed A/T,Hybrid,437.0HP 3.4L V6 Cylinder Engine Gas/Electric Hybrid
1651,Ford,Mustang Mach-E GT,1-Speed Automatic,NaN,Electric
1697,Cadillac,LYRIQ Luxury,A/T,Electric,500.0HP Electric Motor Electric Fuel System
1699,Mercedes-Benz,AMG GT 53 Base,Transmission w/Dual Shift Mode,Hybrid,429.0HP 3.0L Straight 6 Cylinder Engine Gasoline/Mild Electric Hybrid
1709,Tesla,Model S P100D,A/T,Electric,518.0HP Electric Motor Electric Fuel System
1731,Chevrolet,Silverado 1500 Hybrid 1HY,4-Speed A/T,Hybrid,332.0HP 6.0L 8 Cylinder Engine Gas/Electric Hybrid
1788,Tesla,Model S 85D,1-Speed A/T,Electric,422.0HP Electric Motor Electric Fuel System
1820,Volvo,XC90 Recharge Plug-In Hybrid T8 Inscription 7 Passenger,8-Speed A/T,Plug-In Hybrid,455.0HP 2.0L 4 Cylinder Engine Plug-In Electric/Gas
1836,Rivian,R1S Adventure Package,A/T,Electric,835.0HP Electric Motor Electric Fuel System
1838,Ford,Fusion Hybrid SE,A/T,Hybrid,188.0HP 2.0L 4 Cylinder Engine Gas/Electric Hybrid
1866,Audi,Q8 55 Premium Plus,8-Speed A/T,Hybrid,335.0HP 3.0L V6 Cylinder Engine Gasoline/Mild Electric Hybrid
1873,Land,Rover Range Rover Sport HST MHEV,8-Speed A/T,Hybrid,395.0HP 3.0L Straight 6 Cylinder Engine Gasoline/Mild Electric Hybrid
1884,Tesla,Model 3 Performance,1-Speed A/T,Electric,271.0HP Electric Motor Electric Fuel System
1888,Tesla,Model S 100D,A/T,Electric,518.0HP Electric Motor Electric Fuel System
1892,Audi,Q8 55 Premium,8-Speed A/T,Hybrid,335.0HP 3.0L V6 Cylinder Engine Gasoline/Mild Electric Hybrid
1899,Lexus,CT 200h Premium,A/T,Hybrid,134.0HP 1.8L 4 Cylinder Engine Gas/Electric Hybrid
1901,Tesla,Model S Performance,1-Speed A/T,Electric,778.0HP Electric Motor Electric Fuel System
1907,Kia,Optima Hybrid EX,6-Speed A/T,Hybrid,199.0HP 2.4L 4 Cylinder Engine Gas/Electric Hybrid
1911,Porsche,Taycan Turbo,A/T,Electric,616.0HP Electric Motor Electric Fuel System
1921,Toyota,Camry Hybrid XLE,CVT Transmission,Hybrid,208.0HP 2.5L 4 Cylinder Engine Gas/Electric Hybrid
1925,Toyota,Tundra Hybrid Capstone,10-Speed A/T,Hybrid,437.0HP 3.4L V6 Cylinder Engine Gas/Electric Hybrid
1929,Kia,Niro Plug-In Hybrid EX,A/T,Plug-In Hybrid,180.0HP 1.6L 4 Cylinder Engine Plug-In Electric/Gas
1933,Acura,MDX Sport Hybrid 3.0L w/Technology Package,7-Speed A/T,Hybrid,321.0HP 3.0L V6 Cylinder Engine Gas/Electric Hybrid
1943,Tesla,Model 3 Standard Range Plus,A/T,Electric,Electric Motor Electric Fuel System
1954,Tesla,Model 3,Automatic,NaN,Electric
1955,Land,Rover Range Rover P400 SE LWB 7 Seat,A/T,Hybrid,395.0HP 3.0L Straight 6 Cylinder Engine Gasoline/Mild Electric Hybrid
1970,Land,Rover Defender 110 SE,8-Speed A/T,Hybrid,395.0HP 3.0L Straight 6 Cylinder Engine Gasoline/Mild Electric Hybrid
2030,RAM,1500 Big Horn,A/T,Hybrid,395.0HP 5.7L 8 Cylinder Engine Gasoline/Mild Electric Hybrid
2066,Chevrolet,Bolt EV LT,A/T,Electric,200.0HP Electric Motor Electric Fuel System
2102,Tesla,Model 3 Long Range,A/T,Electric,271.0HP Electric Motor Electric Fuel System
2116,Tesla,Model S P100D,1-Speed A/T,Electric,Electric Motor Electric Fuel System
2124,Tesla,Model X Long Range,1-Speed A/T,Electric,518.0HP Electric Motor Electric Fuel System
2137,Ford,Fusion Hybrid SE Hybrid,CVT Transmission,Hybrid,188.0HP 2.0L 4 Cylinder Engine Gas/Electric Hybrid
2152,Lexus,CT 200h Premium,A/T,Hybrid,134.0HP 1.8L 4 Cylinder Engine Gas/Electric Hybrid
2181,Tesla,Model 3 Base,A/T,Electric,271.0HP Electric Motor Electric Fuel System
2184,Rivian,R1S Adventure Package,1-Speed A/T,Electric,835.0HP Electric Motor Electric Fuel System
2191,Tesla,Model 3 Performance,1-Speed A/T,Electric,455.0HP Electric Motor Electric Fuel System
2194,Kia,Sorento Hybrid EX,6-Speed A/T,Hybrid,227.0HP 1.6L 4 Cylinder Engine Gas/Electric Hybrid
2209,Tesla,Model 3 Standard Range Plus,A/T,Electric,Electric Motor Electric Fuel System
2231,Tesla,Model 3 Long Range,A/T,Electric,Electric Motor Electric Fuel System
2233,Rivian,R1T Launch Edition,A/T,Electric,835.0HP Electric Motor Electric Fuel System
2236,Tesla,Model 3 Mid Range,A/T,Electric,271.0HP Electric Motor Electric Fuel System
2250,Tesla,Model 3 Long Range,A/T,Electric,425.0HP Electric Motor Electric Fuel System
2269,Jeep,Wrangler Unlimited 4xe Sahara,8-Speed A/T,Plug-In Hybrid,375.0HP 2.0L 4 Cylinder Engine Plug-In Electric/Gas
2275,BMW,i8 Base,Transmission w/Dual Shift Mode,Plug-In Hybrid,357.0HP 1.5L 3 Cylinder Engine Plug-In Electric/Gas
2322,Tesla,Model Y Performance,A/T,Electric,455.0HP Electric Motor Electric Fuel System
2343,Tesla,Model 3 Long Range,1-Speed A/T,Electric,271.0HP Electric Motor Electric Fuel System
2345,Tesla,Model Y Long Range,A/T,Electric,425.0HP Electric Motor Electric Fuel System
2348,BMW,X5 xDrive40e,Automatic,Hybrid,Electric
2351,Land,Rover Range Rover Sport P400 SE Dynamic,8-Speed A/T,Hybrid,395.0HP 3.0L Straight 6 Cylinder Engine Gasoline/Mild Electric Hybrid
2372,Jaguar,E-PACE 300 Sport,9-Speed A/T,Hybrid,296.0HP 2.0L 4 Cylinder Engine Gasoline/Mild Electric Hybrid
2378,Audi,A6 45 Premium Plus,A/T,Hybrid,248.0HP 2.0L 4 Cylinder Engine Gasoline/Mild Electric Hybrid
2379,Tesla,Model S P100D,1-Speed Automatic,NaN,Electric
2407,Rivian,R1S Adventure Package,A/T,Electric,533.0HP Electric Motor Electric Fuel System
2414,Lexus,RX 450h Base,A/T,Hybrid,245.0HP 3.5L V6 Cylinder Engine Gas/Electric Hybrid
2426,Volkswagen,ID.4 Pro S,1-Speed A/T,Electric,295.0HP Electric Motor Electric Fuel System

In [267]:
df['fuel_type']=(df['fuel_type'].where(
    ~df['engine']
    .str.contains('Electric',case=False,na=False),
    df['fuel_type'].fillna('Electric')))

In [268]:
missing_info={}
for col in Categorical_Columns:
    if df[col].isnull().sum()>0:
        missing_count=(df[col].isnull().sum()/len(df))*100
        missing_info[col]=round(missing_count,2)
print("\n The Categorical columns with missing percentage is:\n")
for col,per in missing_info.items():
    print(f"{col}: {per}%")

 The Categorical columns with missing percentage is:

fuel_type: 0.12%
accident: 2.82%

In [269]:
df[df['fuel_type'].isna()]

,brand,model,model_year,milage,fuel_type,engine,transmission,ext_col,int_col,accident,clean_title,price,Accident_Occurred,Engine_Capacity,Horse_Power
383,Ford,Mustang Mach-E Select,2023,923.0,NaN,Standard Range Battery,Automatic,Rapid Red Metallic Tinted Clearcoat,Black Onyx,None reported,Unknown,46998.0,NO,NaN,NaN
456,Kia,EV6 Wind,2022,11945.0,NaN,111.2Ah / FR 70kW / RR 160kW (697V),Automatic,Glacier,Black,None reported,Unknown,38998.0,NO,NaN,NaN
555,Tesla,Model 3 Long Range,2022,3077.0,NaN,Dual Motor - Standard,Automatic,Silver,Black,None reported,Unknown,44998.0,NO,NaN,NaN
1800,Tesla,Model Y Long Range,2022,4665.0,NaN,Dual Motor - Standard,Automatic,Silver,Black,None reported,Unknown,46598.0,NO,NaN,NaN
2613,Tesla,Model Y Long Range,2022,9411.0,NaN,Dual Motor - Standard,Automatic,Silver,Black,None reported,Unknown,47998.0,NO,NaN,NaN

In [270]:
df.loc[
    df['engine']
    .str.contains('Standard Range Battery',case=False,na=False),
    ['brand','model','transmission','fuel_type','engine']
    ]

,brand,model,transmission,fuel_type,engine
383,Ford,Mustang Mach-E Select,Automatic,NaN,Standard Range Battery

In [271]:
df['fuel_type']=(df['fuel_type'].where(
    ~df['engine']
    .str.contains('Standard Range Battery',case=False,na=False),
    df['fuel_type'].fillna('Electric')))

In [272]:
df[df['fuel_type'].isna()]

,brand,model,model_year,milage,fuel_type,engine,transmission,ext_col,int_col,accident,clean_title,price,Accident_Occurred,Engine_Capacity,Horse_Power
456,Kia,EV6 Wind,2022,11945.0,NaN,111.2Ah / FR 70kW / RR 160kW (697V),Automatic,Glacier,Black,None reported,Unknown,38998.0,NO,NaN,NaN
555,Tesla,Model 3 Long Range,2022,3077.0,NaN,Dual Motor - Standard,Automatic,Silver,Black,None reported,Unknown,44998.0,NO,NaN,NaN
1800,Tesla,Model Y Long Range,2022,4665.0,NaN,Dual Motor - Standard,Automatic,Silver,Black,None reported,Unknown,46598.0,NO,NaN,NaN
2613,Tesla,Model Y Long Range,2022,9411.0,NaN,Dual Motor - Standard,Automatic,Silver,Black,None reported,Unknown,47998.0,NO,NaN,NaN

In [273]:
df.loc[
    df['engine']
    .str.contains('Dual Motor - Standard',case=False,na=False),
    ['brand','model','engine','fuel_type','transmission']
]

      brand               model                 engine fuel_type transmission
555   Tesla  Model 3 Long Range  Dual Motor - Standard       NaN    Automatic
1800  Tesla  Model Y Long Range  Dual Motor - Standard       NaN    Automatic
2613  Tesla  Model Y Long Range  Dual Motor - Standard       NaN    Automatic

In [274]:
df['fuel_type']=(
    df['fuel_type'].where(
        ~df['engine']
        .str.contains('Dual Motor - Standard',case=False,na=False),
        df['fuel_type'].fillna('Electric')
    )
)

In [275]:
df[df['fuel_type'].isna()]

,brand,model,model_year,milage,fuel_type,engine,transmission,ext_col,int_col,accident,clean_title,price,Accident_Occurred,Engine_Capacity,Horse_Power
456,Kia,EV6 Wind,2022,11945.0,NaN,111.2Ah / FR 70kW / RR 160kW (697V),Automatic,Glacier,Black,None reported,Unknown,38998.0,NO,NaN,NaN

In [276]:
df.loc[456, 'engine']

'111.2Ah / FR 70kW / RR 160kW (697V)'

In [277]:
df.loc[456, 'fuel_type'] = 'Electric'

In [278]:
df.loc[456, 'fuel_type']

'Electric'

In [279]:
df[df['fuel_type'].isna()]

Empty DataFrame
Columns: [brand, model, model_year, milage, fuel_type, engine, transmission, ext_col, int_col, accident, clean_title, price, Accident_Occurred, Engine_Capacity, Horse_Power]
Index: []

In [280]:
missing_info={}
for col in Categorical_Columns:
    if df[col].isnull().sum()>0:
        missing_count=(df[col].isnull().sum()/len(df))*100
        missing_info[col]=round(missing_count,2)
print("\n The Categorical columns with missing percentage is:\n")
for col,per in missing_info.items():
    print(f"{col}: {per}%")

 The Categorical columns with missing percentage is:

accident: 2.82%

In [282]:
df['accident'].head(50)

0     At least 1 accident or damage reported
1     At least 1 accident or damage reported
2                              None reported
3                              None reported
4                              None reported
5                              None reported
6                              None reported
7                              None reported
8                              None reported
9                              None reported
10                             None reported
11                             None reported
12                             None reported
13                             None reported
14                             None reported
15                             None reported
16                             None reported
17                             None reported
18                             None reported
19                             None reported
20                                       NaN
21                             None reported
22                             None reported
23                             None reported
24                             None reported
25                             None reported
26                             None reported
27                             None reported
28                             None reported
29                             None reported
30                             None reported
31    At least 1 accident or damage reported
32                             None reported
33                             None reported
34                             None reported
35                             None reported
36                             None reported
37                             None reported
38                             None reported
39    At least 1 accident or damage reported
40                             None reported
41                             None reported
42    At least 1 accident or damage reported
43                             None reported
44                             None reported
45    At least 1 accident or damage reported
46                             None reported
47    At least 1 accident or damage reported
48                             None reported
49                             None reported
Name: accident, dtype: str

In [283]:
df['accident'].isna().sum()

np.int64(113)

In [284]:
df[df['accident'].isna()]

,brand,model,model_year,milage,fuel_type,engine,transmission,ext_col,int_col,accident,clean_title,price,Accident_Occurred,Engine_Capacity,Horse_Power
20,Genesis,GV70 3.5T Sport,2023,5400.0,Gasoline,375.0HP 3.5L V6 Cylinder Engine Gasoline Fuel,8-Speed A/T,Green,Beige,NaN,Unknown,60000.0,YES,3.5,375.0
89,Subaru,Forester 2.5 X,2004,210703.0,Gasoline,165.0HP 2.5L 4 Cylinder Engine Gasoline Fuel,M/T,Green,Beige,NaN,Unknown,2300.0,YES,2.5,165.0
128,Audi,Q7 3.0T Premium Plus,2015,98527.0,Gasoline,280.0HP 3.0L V6 Cylinder Engine Gasoline Fuel,8-Speed A/T,Black,Black,NaN,Unknown,9995.0,YES,3.0,280.0
129,Lucid,Air Pure,2023,1300.0,Electric,620.0HP Electric Motor Electric Fuel System,A/T,Black,Gray,NaN,Unknown,86900.0,YES,NaN,620.0
131,Audi,TTS 2.0T Premium Plus,2012,72922.0,Gasoline,265.0HP 2.0L 4 Cylinder Engine Gasoline Fuel,6-Speed A/T,White,Black,NaN,Unknown,25999.0,YES,2.0,265.0
139,Porsche,911 Carrera S,2013,18494.0,Gasoline,400.0HP 3.8L Flat 6 Cylinder Engine Gasoline Fuel,7-Speed M/T,Black,Black,NaN,Unknown,86900.0,YES,3.8,400.0
224,Maserati,Ghibli S Q4,2015,28700.0,Gasoline,404.0HP 3.0L V6 Cylinder Engine Gasoline Fuel,8-Speed A/T,White,Red,NaN,Unknown,24900.0,YES,3.0,404.0
235,BMW,M6 Base,2016,45800.0,Gasoline,560.0HP 4.4L 8 Cylinder Engine Gasoline Fuel,7-Speed A/T,Gold,Black,NaN,Unknown,36800.0,YES,4.4,560.0
357,Mercedes-Benz,Sprinter 4500 High Roof,2019,16813.0,Diesel,188.0HP 3.0L V6 Cylinder Engine Diesel Fuel,Transmission w/Dual Shift Mode,Gray,Black,NaN,Unknown,45900.0,YES,3.0,188.0
376,Hyundai,Santa Fe SEL,2022,26895.0,Gasoline,2.5L I4 16V PDI DOHC,8-Speed Automatic,Quartz White,Black,NaN,Unknown,29800.0,YES,2.5,NaN
426,Ford,Transit Connect XL,2018,66770.0,E85 Flex Fuel,169.0HP 2.5L 4 Cylinder Engine Flex Fuel Capability,6-Speed A/T,Red,–,NaN,Unknown,21500.0,YES,2.5,169.0
519,Mercedes-Benz,GLK-Class GLK 350,2013,99200.0,Gasoline,302.0HP 3.5L V6 Cylinder Engine Gasoline Fuel,A/T,Silver,Black,NaN,Unknown,11495.0,YES,3.5,302.0
526,Rivian,R1S Adventure Package,2023,250.0,Electric,835.0HP Electric Motor Electric Fuel System,A/T,Red,Black,NaN,Unknown,94000.0,YES,NaN,835.0
599,Land,Rover Range Rover 5.0L Supercharged Autobiography LWB,2018,36632.0,Gasoline,518.0HP 5.0L 8 Cylinder Engine Gasoline Fuel,8-Speed A/T,Blue,Blue,NaN,Unknown,72567.0,YES,5.0,518.0
623,Bentley,Bentayga Speed,2020,15109.0,Gasoline,6.0L W12 48V PDI DOHC Twin Turbo,8-Speed Automatic,Ice,Beluga Hide,NaN,Unknown,162950.0,YES,6.0,NaN
640,Mercedes-Benz,AMG G 63 4MATIC,2022,2000.0,Gasoline,577.0HP 4.0L 8 Cylinder Engine Gasoline Fuel,Transmission w/Dual Shift Mode,Black,Black,NaN,Unknown,244896.0,YES,4.0,577.0
649,BMW,i8 Base,2019,18421.0,Plug-In Hybrid,369.0HP 1.5L 3 Cylinder Engine Plug-In Electric/Gas,6-Speed A/T,Black,Black,NaN,Unknown,85000.0,YES,1.5,369.0
701,Lexus,LX 600 Premium,2023,1500.0,Gasoline,409.0HP 3.4L V6 Cylinder Engine Gasoline Fuel,10-Speed A/T,Gray,Black,NaN,Unknown,119500.0,YES,3.4,409.0
765,Audi,S8 4.2 quattro,2003,126000.0,Gasoline,360.0HP 4.2L 8 Cylinder Engine Gasoline Fuel,Transmission w/Dual Shift Mode,Gray,Black,NaN,Unknown,13850.0,YES,4.2,360.0
780,BMW,M440 i,2021,13700.0,Hybrid,382.0HP 3.0L Straight 6 Cylinder Engine Gasoline/Mild Electric Hybrid,8-Speed A/T,Black,Beige,NaN,Unknown,60000.0,YES,3.0,382.0
816,GMC,Acadia SLE,2020,30426.0,Gasoline,2.5L I4 16V GDI DOHC,9-Speed Automatic,Ebony Twilight Metallic,Jet Black,NaN,Unknown,29645.0,YES,2.5,NaN
865,INFINITI,FX50 Base,2011,84900.0,Gasoline,390.0HP 5.0L 8 Cylinder Engine Gasoline Fuel,7-Speed A/T,Silver,Black,NaN,Unknown,22450.0,YES,5.0,390.0
870,Kia,Telluride SX,2020,55400.0,Gasoline,291.0HP 3.8L V6 Cylinder Engine Gasoline Fuel,8-Speed A/T,Green,White,NaN,Unknown,36500.0,YES,3.8,291.0
901,Ford,Mustang SVT Cobra,2003,97496.0,Gasoline,390.0HP 4.6L 8 Cylinder Engine Gasoline Fuel,6-Speed M/T,Gray,Gray,NaN,Unknown,24500.0,YES,4.6,390.0
913,Bentley,Continental GT Speed,2009,57800.0,Gasoline,600.0HP 6.0L 12 Cylinder Engine Gasoline Fuel,6-Speed A/T,Blue,Beige,NaN,Unknown,59400.0,YES,6.0,600.0
928,Ford,F-250 XL,2021,77699.0,Diesel,6.7L V8 32V DDI OHV Turbo Diesel,Automatic,White,Medium Earth Gray,NaN,Unknown,49883.0,YES,6.7,NaN
944,Lincoln,MKC Reserve,2019,35469.0,Gasoline,2.3L I4 16V GDI DOHC Turbo,6-Speed Automatic,Black,–,NaN,Unknown,30890.0,YES,2.3,NaN
967,Nissan,Rogue SL,2017,78110.0,Gasoline,170.0HP 2.5L 4 Cylinder Engine Gasoline Fuel,A/T,Silver,Black,NaN,Unknown,17500.0,YES,2.5,170.0
983,Land,Rover Range Rover Sport HST MHEV,2020,19000.0,Hybrid,395.0HP 3.0L Straight 6 Cylinder Engine Gasoline/Mild Electric Hybrid,Transmission w/Dual Shift Mode,Silver,Black,NaN,Unknown,74900.0,YES,3.0,395.0
1001,Porsche,Cayman Base,2011,66000.0,Gasoline,265.0HP 2.9L Flat 6 Cylinder Engine Gasoline Fuel,A/T,Black,Brown,NaN,Unknown,28000.0,YES,2.9,265.0
1042,Toyota,Tacoma Double Cab,2007,24985.0,Gasoline,236.0HP 4.0L V6 Cylinder Engine Gasoline Fuel,5-Speed A/T,Silver,Silver,NaN,Unknown,33580.0,YES,4.0,236.0
1140,Audi,S5 3.0T Premium Plus,2014,67900.0,Gasoline,333.0HP 3.0L V6 Cylinder Engine Gasoline Fuel,6-Speed M/T,Silver,Black,NaN,Unknown,25990.0,YES,3.0,333.0
1144,Mercedes-Benz,CLS-Class CLS500,2006,28950.0,Gasoline,302.0HP 5.0L 8 Cylinder Engine Gasoline Fuel,7-Speed A/T,Blue,Beige,NaN,Unknown,16750.0,YES,5.0,302.0
1153,Volvo,XC70 3.2,2008,46700.0,Gasoline,235.0HP 3.2L Straight 6 Cylinder Engine Gasoline Fuel,6-Speed A/T,White,Beige,NaN,Unknown,11400.0,YES,3.2,235.0
1188,Jeep,Grand Cherokee L Laredo,2022,22109.0,Gasoline,3.6L V6 24V MPFI DOHC,Automatic,Bright White Clearcoat,Global Black,NaN,Unknown,43389.0,YES,3.6,NaN
1240,Porsche,911 Carrera S Cabriolet,2007,28844.0,Gasoline,3.8L H6 24V MPFI DOHC,6-Speed Manual,White,Beige,NaN,Unknown,69995.0,YES,3.8,NaN
1244,Mazda,Mazda6 Touring,2021,19000.0,Gasoline,187.0HP 2.5L 4 Cylinder Engine Gasoline Fuel,A/T,Blue,Black,NaN,Unknown,25900.0,YES,2.5,187.0
1386,BMW,750 i xDrive,2020,25108.0,Gasoline,523.0HP 4.4L 8 Cylinder Engine Gasoline Fuel,8-Speed A/T,Black,Black,NaN,Unknown,66000.0,YES,4.4,523.0
1403,Jaguar,XF XFR-S,2013,4279.0,Gasoline,550.0HP 5.0L 8 Cylinder Engine Gasoline Fuel,8-Speed A/T,White,Black,NaN,Unknown,70000.0,YES,5.0,550.0
1452,Jeep,Grand Cherokee Altitude,2020,35289.0,Gasoline,3.6L V6 24V MPFI DOHC,8-Speed Automatic,Granite Crystal Clearcoat Metallic,Black,NaN,Unknown,35470.0,YES,3.6,NaN
1497,Acura,RSX Type S,2006,71400.0,Gasoline,201.0HP 2.0L 4 Cylinder Engine Gasoline Fuel,6-Speed M/T,Black,Gray,NaN,Unknown,14990.0,YES,2.0,201.0
1504,BMW,X5 xDrive35i,2014,120000.0,Gasoline,300.0HP 3.0L Straight 6 Cylinder Engine Gasoline Fuel,Transmission w/Dual Shift Mode,Black,Black,NaN,Unknown,20000.0,YES,3.0,300.0
1527,Hyundai,Genesis 3.8,2015,61300.0,Gasoline,311.0HP 3.8L V6 Cylinder Engine Gasoline Fuel,8-Speed A/T,Silver,Gray,NaN,Unknown,20150.0,YES,3.8,311.0
1586,Ford,F-250 XLT,2022,36294.0,Diesel,6.7L V8 32V DDI OHV Turbo Diesel,Automatic,Oxford White,Medium Earth Gray,NaN,Unknown,77535.0,YES,6.7,NaN
1619,Jeep,Gladiator Sport,2021,5779.0,Gasoline,3.6L V6 24V MPFI DOHC,8-Speed Automatic,Firecracker Red Clearcoat,Black,NaN,Unknown,41329.0,YES,3.6,NaN
1635,Chevrolet,Silverado 3500 LTZ,2018,92149.0,Diesel,6.6L V8 32V DDI OHV Turbo Diesel,6-Speed Automatic,Black,Jet Black,NaN,Unknown,52889.0,YES,6.6,NaN
1670,Ford,F-250 Lariat,2017,72128.0,E85 Flex Fuel,6.2L V8 16V MPFI SOHC Flexible Fuel,6-Speed Automatic,White,Camel,NaN,Unknown,45985.0,YES,6.2,NaN
1706,Ford,Bronco Sport Outer Banks,2021,28105.0,Gasoline,1.5L I3 12V PDI DOHC Turbo,8-Speed Automatic,Kodiak Brown Metallic,Ebony,NaN,Unknown,32455.0,YES,1.5,NaN
1752,MINI,Convertible Cooper,2022,15544.0,Gasoline,134.0HP 1.5L 3 Cylinder Engine Gasoline Fuel,A/T,Blue,Brown,NaN,Unknown,28000.0,YES,1.5,134.0
1780,Cadillac,Escalade ESV Sport,2021,4500.0,Gasoline,420.0HP 6.2L 8 Cylinder Engine Gasoline Fuel,10-Speed A/T,White,Beige,NaN,Unknown,105000.0,YES,6.2,420.0
1784,Ford,F-150 XLT,2021,77107.0,Gasoline,3.5L V6 24V PDI DOHC Twin Turbo,10-Speed Automatic,Agate Black Metallic,Black,NaN,Unknown,39995.0,YES,3.5,NaN
1945,Chevrolet,Cruze LT,2012,148377.0,Gasoline,138.0HP 1.4L 4 Cylinder Engine Gasoline Fuel,6-Speed A/T,Blue,Black,NaN,Unknown,5500.0,YES,1.4,138.0
1953,BMW,X5 xDrive35i,2013,76309.0,Gasoline,300.0HP 3.0L Straight 6 Cylinder Engine Gasoline Fuel,A/T,Silver,Black,NaN,Unknown,12000.0,YES,3.0,300.0
1955,Land,Rover Range Rover P400 SE LWB 7 Seat,2023,4126.0,Hybrid,395.0HP 3.0L Straight 6 Cylinder Engine Gasoline/Mild Electric Hybrid,A/T,Black,Beige,NaN,Unknown,155000.0,YES,3.0,395.0
1970,Land,Rover Defender 110 SE,2020,29700.0,Hybrid,395.0HP 3.0L Straight 6 Cylinder Engine Gasoline/Mild Electric Hybrid,8-Speed A/T,Green,Black,NaN,Unknown,68000.0,YES,3.0,395.0
2035,INFINITI,QX80 SENSORY,2023,8600.0,Gasoline,400.0HP 5.6L 8 Cylinder Engine Gasoline Fuel,7-Speed A/T,Black,Brown,NaN,Unknown,78990.0,YES,5.6,400.0
2037,Hyundai,Genesis Coupe 2.0T,2010,65000.0,Gasoline,210.0HP 2.0L 4 Cylinder Engine Gasoline Fuel,A/T,Gray,Black,NaN,Unknown,8900.0,YES,2.0,210.0
2090,Honda,Passport TrailSport,2023,11649.0,Gasoline,280.0HP 3.5L V6 Cylinder Engine Gasoline Fuel,9-Speed A/T,Black,Black,NaN,Unknown,39999.0,YES,3.5,280.0
2107,Audi,TT RS Base,2012,54900.0,Gasoline,360.0HP 2.5L 5 Cylinder Engine Gasoline Fuel,6-Speed M/T,White,Brown,NaN,Unknown,28900.0,YES,2.5,360.0
2123,Nissan,Pathfinder SL,2018,167000.0,Gasoline,284.0HP 3.5L V6 Cylinder Engine Gasoline Fuel,A/T,Black,Beige,NaN,Unknown,14500.0,YES,3.5,284.0
2184,Rivian,R1S Adventure Package,2023,250.0,Electric,835.0HP Electric Motor Electric Fuel System,1-Speed A/T,Green,Black,NaN,Unknown,97500.0,YES,NaN,835.0
2186,INFINITI,QX60 Base,2014,95400.0,Gasoline,265.0HP 3.5L V6 Cylinder Engine Gasoline Fuel,A/T,White,Beige,NaN,Unknown,14195.0,YES,3.5,265.0
2206,Chevrolet,Silverado 1500 RST,2020,26177.0,Gasoline,5.3L V8 16V GDI OHV,Automatic,Shadow Gray Metallic,Jet Black,NaN,Unknown,41986.0,YES,5.3,NaN
2232,Ford,Transit-350 Base,2018,235000.0,Gasoline,275.0HP 3.7L V6 Cylinder Engine Gasoline Fuel,A/T,White,Gray,NaN,Unknown,18000.0,YES,3.7,275.0
2258,BMW,750 iL,2001,53814.0,Gasoline,326.0HP 5.4L 12 Cylinder Engine Gasoline Fuel,5-Speed A/T,Gray,Gray,NaN,Unknown,11800.0,YES,5.4,326.0
2288,RAM,2500 Tradesman,2020,41000.0,Gasoline,410.0HP 6.4L 8 Cylinder Engine Gasoline Fuel,8-Speed A/T,White,Gray,NaN,Unknown,45515.0,YES,6.4,410.0
2328,Cadillac,Escalade ESV Platinum Edition,2013,119000.0,E85 Flex Fuel,403.0HP 6.2L 8 Cylinder Engine Flex Fuel Capability,A/T,Black,Black,NaN,Unknown,20500.0,YES,6.2,403.0
2364,Porsche,911 Carrera 4S,2003,90000.0,Gasoline,315.0HP 3.6L Flat 6 Cylinder Engine Gasoline Fuel,6-Speed M/T,Silver,Black,NaN,Unknown,24000.0,YES,3.6,315.0
2368,Chevrolet,Silverado 1500 LT,2019,36021.0,Gasoline,2.7L I4 16V GDI DOHC Turbo,Automatic,Cajun Red Tintcoat,Jet Black,NaN,Unknown,35670.0,YES,2.7,NaN
2386,Hyundai,Genesis Coupe 2.0T R-Spec,2013,55000.0,Gasoline,260.0HP 2.0L 4 Cylinder Engine Gasoline Fuel,6-Speed M/T,White,Red,NaN,Unknown,18000.0,YES,2.0,260.0
2450,Lexus,GX 460 Luxury,2020,37366.0,Gasoline,4.6L V8 32V MPFI DOHC,6-Speed Automatic,White,–,NaN,Unknown,51890.0,YES,4.6,NaN
2519,Porsche,Panamera 4,2011,85000.0,Gasoline,300.0HP 3.6L V6 Cylinder Engine Gasoline Fuel,A/T,Gray,Beige,NaN,Unknown,21500.0,YES,3.6,300.0
2541,Chevrolet,Silverado 2500 WT,2018,141195.0,E85 Flex Fuel,6.0L V8 16V MPFI OHV Flexible Fuel,6-Speed Automatic,Summit White,Dark Ash,NaN,Unknown,28499.0,YES,6.0,NaN
2594,Porsche,Panamera S,2012,49000.0,Gasoline,400.0HP 4.8L 8 Cylinder Engine Gasoline Fuel,7-Speed A/T,White,Black,NaN,Unknown,41500.0,YES,4.8,400.0
2597,Chrysler,200 Limited,2015,95271.0,E85 Flex Fuel,184.0HP 2.4L 4 Cylinder Engine Flex Fuel Capability,A/T,Black,Black,NaN,Unknown,12468.0,YES,2.4,184.0
2602,Lotus,Elise Base,2005,25250.0,Gasoline,190.0HP 1.8L 4 Cylinder Engine Gasoline Fuel,M/T,Red,Black,NaN,Unknown,44000.0,YES,1.8,190.0
2641,Chevrolet,Suburban LTZ,2016,135484.0,Gasoline,5.3L V8 16V GDI OHV,6-Speed Automatic,Tungsten Metallic,Cocoa / Dune,NaN,Unknown,29748.0,YES,5.3,NaN
2643,BMW,M3 Base,2012,7982.0,Gasoline,414.0HP 4.0L 8 Cylinder Engine Gasoline Fuel,7-Speed A/T,Silver,Red,NaN,Unknown,51900.0,YES,4.0,414.0
2649,Honda,Civic Sport,2020,22227.0,Gasoline,2.0L I4 16V MPFI DOHC,Automatic CVT,Red,Black,NaN,Unknown,25980.0,YES,2.0,NaN
2760,Jeep,Gladiator Overland,2020,20655.0,Gasoline,3.6L V6 24V MPFI DOHC,8-Speed Automatic,Firecracker Red Clearcoat,Black,NaN,Unknown,42850.0,YES,3.6,NaN
2805,Porsche,911 Carrera Cabriolet,2001,47885.0,Gasoline,300.0HP 3.4L Flat 6 Cylinder Engine Gasoline Fuel,6-Speed M/T,Gray,Black,NaN,Unknown,31995.0,YES,3.4,300.0
2821,Porsche,Boxster Base,1997,132800.0,Gasoline,201.0HP 2.5L Flat 6 Cylinder Engine Gasoline Fuel,5-Speed M/T,Red,Beige,NaN,Unknown,8500.0,YES,2.5,201.0
2857,Toyota,Camry Solara SE,2008,57852.0,Gasoline,210.0HP 3.3L V6 Cylinder Engine Gasoline Fuel,A/T,Silver,Gray,NaN,Unknown,13900.0,YES,3.3,210.0
2876,Lincoln,Navigator L Reserve,2019,49131.0,Gasoline,3.5L V6 24V PDI DOHC Twin Turbo,10-Speed Automatic,Tan,–,NaN,Unknown,55460.0,YES,3.5,NaN
2895,Alfa,Romeo Giulia Ti,2017,56910.0,Gasoline,280.0HP 2.0L 4 Cylinder Engine Gasoline Fuel,Transmission w/Dual Shift Mode,Blue,Black,NaN,Unknown,23000.0,YES,2.0,280.0
2911,Ford,F-150 Lariat,2021,36821.0,Gasoline,3.5L V6 24V PDI DOHC Twin Turbo,Automatic,Agate Black Metallic,Black,NaN,Unknown,49273.0,YES,3.5,NaN
2968,Dodge,Challenger SRT Demon,2018,2620.0,Gasoline,808.0HP 6.2L 8 Cylinder Engine Gasoline Fuel,8-Speed A/T,Black,Black,NaN,Unknown,155700.0,YES,6.2,808.0
3010,Honda,Pilot EX-L,2020,28886.0,Gasoline,3.5L V6 24V GDI SOHC,6-Speed Automatic,Gray,Gray,NaN,Unknown,35645.0,YES,3.5,NaN
3025,Mercedes-Benz,CLS-Class CLS 63 AMG S-Model 4MATIC,2014,64500.0,Gasoline,577.0HP 5.5L 8 Cylinder Engine Gasoline Fuel,7-Speed A/T,Silver,Black,NaN,Unknown,37500.0,YES,5.5,577.0
3031,GMC,Sierra 2500 AT4,2022,22600.0,Diesel,6.6L V8 32V DDI OHV Turbo Diesel,Automatic,Ebony Twilight Metallic,Jet Black,NaN,Unknown,76740.0,YES,6.6,NaN
3103,Jeep,Grand Cherokee L Laredo,2021,23588.0,Gasoline,3.6L V6 24V MPFI DOHC,8-Speed Automatic,Metallic,Global Black,NaN,Unknown,38633.0,YES,3.6,NaN
3172,Chevrolet,Caprice Classic Base,1996,60000.0,Gasoline,260.0HP 5.7L 8 Cylinder Engine Gasoline Fuel,A/T,Purple,Gray,NaN,Unknown,18500.0,YES,5.7,260.0
3179,Rolls-Royce,Wraith Base,2016,21000.0,Gasoline,624.0HP 6.6L 12 Cylinder Engine Gasoline Fuel,A/T,Brown,Black,NaN,Unknown,217000.0,YES,6.6,624.0
3183,Toyota,Tundra TRD Pro,2016,51400.0,E85 Flex Fuel,381.0HP 5.7L 8 Cylinder Engine Flex Fuel Capability,6-Speed A/T,Black,Black,NaN,Unknown,39900.0,YES,5.7,381.0
3209,Ford,Explorer ST,2022,10500.0,Gasoline,400.0HP 3.0L V6 Cylinder Engine Gasoline Fuel,Transmission w/Dual Shift Mode,Black,Black,NaN,Unknown,50000.0,YES,3.0,400.0
3318,Ford,Bronco Outer Banks,2023,1800.0,Gasoline,275.0HP 2.3L 4 Cylinder Engine Gasoline Fuel,10-Speed A/T,Gray,Blue,NaN,Unknown,54900.0,YES,2.3,275.0
3433,Porsche,911 Turbo,2021,11938.0,Gasoline,572.0HP 3.8L Flat 6 Cylinder Engine Gasoline Fuel,Transmission w/Dual Shift Mode,Black,–,NaN,Unknown,209000.0,YES,3.8,572.0
3465,Porsche,911 Carrera C4S,2006,65000.0,Gasoline,355.0HP 3.8L Flat 6 Cylinder Engine Gasoline Fuel,6-Speed M/T,Blue,Gray,NaN,Unknown,43000.0,YES,3.8,355.0
3575,Porsche,911 Carrera,2021,7400.0,Gasoline,379.0HP 3.0L Flat 6 Cylinder Engine Gasoline Fuel,8-Speed A/T,Red,Black,NaN,Unknown,116999.0,YES,3.0,379.0
3670,Cadillac,XLR V,2008,64800.0,Gasoline,443.0HP 4.4L 8 Cylinder Engine Gasoline Fuel,6-Speed A/T,Black,Black,NaN,Unknown,24700.0,YES,4.4,443.0
3677,Porsche,Boxster Base,2005,75000.0,Gasoline,240.0HP 2.7L Flat 6 Cylinder Engine Gasoline Fuel,5-Speed M/T,Silver,Black,NaN,Unknown,17500.0,YES,2.7,240.0
3681,Alfa,Romeo Giulia Ti,2020,23339.0,Gasoline,2.0L I4 16V GDI SOHC Turbo,8-Speed Automatic,Rosso,Black,NaN,Unknown,34645.0,YES,2.0,NaN
3707,Porsche,718 Cayman GT4,2021,2100.0,Gasoline,414.0HP 4.0L Flat 6 Cylinder Engine Gasoline Fuel,6-Speed M/T,Yellow,Black,NaN,Unknown,136900.0,YES,4.0,414.0
3768,GMC,HUMMER EV Edition 1,2023,940.0,Electric,Electric Motor Electric Fuel System,A/T,White,Black,NaN,Unknown,146000.0,YES,NaN,NaN
3794,Ford,Thunderbird Deluxe,2004,39000.0,Gasoline,280.0HP 3.9L 8 Cylinder Engine Gasoline Fuel,A/T,Black,Beige,NaN,Unknown,22000.0,YES,3.9,280.0
3817,Ford,F-250 King Ranch,2021,93400.0,Diesel,475.0HP 6.7L 8 Cylinder Engine Diesel Fuel,10-Speed A/T,Red,Brown,NaN,Unknown,69995.0,YES,6.7,475.0
3836,Audi,S6 4.0T Prestige,2013,53900.0,Gasoline,420.0HP 4.0L 8 Cylinder Engine Gasoline Fuel,7-Speed A/T,Black,Black,NaN,Unknown,27450.0,YES,4.0,420.0
3861,Ford,Escape SEL,2020,42000.0,Gasoline,181.0HP 1.5L 3 Cylinder Engine Gasoline Fuel,A/T,White,Beige,NaN,Unknown,19000.0,YES,1.5,181.0
3865,Alfa,Romeo Giulia Quadrifoglio,2018,28644.0,Gasoline,505.0HP 2.9L V6 Cylinder Engine Gasoline Fuel,8-Speed A/T,Black,Black,NaN,Unknown,41500.0,YES,2.9,505.0
3901,Mazda,CX-5 Grand Touring,2021,24781.0,Gasoline,2.5L I4 16V GDI DOHC,6-Speed Automatic,Machine Gray Metallic,Black,NaN,Unknown,28991.0,YES,2.5,NaN
3918,Porsche,911 Carrera Cabriolet,1996,38000.0,–,–,Transmission w/Dual Shift Mode,Blue,Gray,NaN,Unknown,75000.0,YES,NaN,NaN
3993,Porsche,911 Carrera S,2021,7008.0,Gasoline,443.0HP 3.0L Flat 6 Cylinder Engine Gasoline Fuel,8-Speed A/T,Gray,Black,NaN,Unknown,151900.0,YES,3.0,443.0
3996,Aston,Martin DB7 Vantage Volante,2003,14900.0,Gasoline,420.0HP 5.9L 12 Cylinder Engine Gasoline Fuel,6-Speed M/T,White,Beige,NaN,Unknown,32850.0,YES,5.9,420.0

In [285]:
df[df['accident'].isna()][
    ['brand', 'model', 'model_year', 'clean_title', 'accident']
]

,brand,model,model_year,clean_title,accident
20,Genesis,GV70 3.5T Sport,2023,Unknown,NaN
89,Subaru,Forester 2.5 X,2004,Unknown,NaN
128,Audi,Q7 3.0T Premium Plus,2015,Unknown,NaN
129,Lucid,Air Pure,2023,Unknown,NaN
131,Audi,TTS 2.0T Premium Plus,2012,Unknown,NaN
139,Porsche,911 Carrera S,2013,Unknown,NaN
224,Maserati,Ghibli S Q4,2015,Unknown,NaN
235,BMW,M6 Base,2016,Unknown,NaN
357,Mercedes-Benz,Sprinter 4500 High Roof,2019,Unknown,NaN
376,Hyundai,Santa Fe SEL,2022,Unknown,NaN
426,Ford,Transit Connect XL,2018,Unknown,NaN
519,Mercedes-Benz,GLK-Class GLK 350,2013,Unknown,NaN
526,Rivian,R1S Adventure Package,2023,Unknown,NaN
599,Land,Rover Range Rover 5.0L Supercharged Autobiography LWB,2018,Unknown,NaN
623,Bentley,Bentayga Speed,2020,Unknown,NaN
640,Mercedes-Benz,AMG G 63 4MATIC,2022,Unknown,NaN
649,BMW,i8 Base,2019,Unknown,NaN
701,Lexus,LX 600 Premium,2023,Unknown,NaN
765,Audi,S8 4.2 quattro,2003,Unknown,NaN
780,BMW,M440 i,2021,Unknown,NaN
816,GMC,Acadia SLE,2020,Unknown,NaN
865,INFINITI,FX50 Base,2011,Unknown,NaN
870,Kia,Telluride SX,2020,Unknown,NaN
901,Ford,Mustang SVT Cobra,2003,Unknown,NaN
913,Bentley,Continental GT Speed,2009,Unknown,NaN
928,Ford,F-250 XL,2021,Unknown,NaN
944,Lincoln,MKC Reserve,2019,Unknown,NaN
967,Nissan,Rogue SL,2017,Unknown,NaN
983,Land,Rover Range Rover Sport HST MHEV,2020,Unknown,NaN
1001,Porsche,Cayman Base,2011,Unknown,NaN
1042,Toyota,Tacoma Double Cab,2007,Unknown,NaN
1140,Audi,S5 3.0T Premium Plus,2014,Unknown,NaN
1144,Mercedes-Benz,CLS-Class CLS500,2006,Unknown,NaN
1153,Volvo,XC70 3.2,2008,Unknown,NaN
1188,Jeep,Grand Cherokee L Laredo,2022,Unknown,NaN
1240,Porsche,911 Carrera S Cabriolet,2007,Unknown,NaN
1244,Mazda,Mazda6 Touring,2021,Unknown,NaN
1386,BMW,750 i xDrive,2020,Unknown,NaN
1403,Jaguar,XF XFR-S,2013,Unknown,NaN
1452,Jeep,Grand Cherokee Altitude,2020,Unknown,NaN
1497,Acura,RSX Type S,2006,Unknown,NaN
1504,BMW,X5 xDrive35i,2014,Unknown,NaN
1527,Hyundai,Genesis 3.8,2015,Unknown,NaN
1586,Ford,F-250 XLT,2022,Unknown,NaN
1619,Jeep,Gladiator Sport,2021,Unknown,NaN
1635,Chevrolet,Silverado 3500 LTZ,2018,Unknown,NaN
1670,Ford,F-250 Lariat,2017,Unknown,NaN
1706,Ford,Bronco Sport Outer Banks,2021,Unknown,NaN
1752,MINI,Convertible Cooper,2022,Unknown,NaN
1780,Cadillac,Escalade ESV Sport,2021,Unknown,NaN
1784,Ford,F-150 XLT,2021,Unknown,NaN
1945,Chevrolet,Cruze LT,2012,Unknown,NaN
1953,BMW,X5 xDrive35i,2013,Unknown,NaN
1955,Land,Rover Range Rover P400 SE LWB 7 Seat,2023,Unknown,NaN
1970,Land,Rover Defender 110 SE,2020,Unknown,NaN
2035,INFINITI,QX80 SENSORY,2023,Unknown,NaN
2037,Hyundai,Genesis Coupe 2.0T,2010,Unknown,NaN
2090,Honda,Passport TrailSport,2023,Unknown,NaN
2107,Audi,TT RS Base,2012,Unknown,NaN
2123,Nissan,Pathfinder SL,2018,Unknown,NaN
2184,Rivian,R1S Adventure Package,2023,Unknown,NaN
2186,INFINITI,QX60 Base,2014,Unknown,NaN
2206,Chevrolet,Silverado 1500 RST,2020,Unknown,NaN
2232,Ford,Transit-350 Base,2018,Unknown,NaN
2258,BMW,750 iL,2001,Unknown,NaN
2288,RAM,2500 Tradesman,2020,Unknown,NaN
2328,Cadillac,Escalade ESV Platinum Edition,2013,Unknown,NaN
2364,Porsche,911 Carrera 4S,2003,Unknown,NaN
2368,Chevrolet,Silverado 1500 LT,2019,Unknown,NaN
2386,Hyundai,Genesis Coupe 2.0T R-Spec,2013,Unknown,NaN
2450,Lexus,GX 460 Luxury,2020,Unknown,NaN
2519,Porsche,Panamera 4,2011,Unknown,NaN
2541,Chevrolet,Silverado 2500 WT,2018,Unknown,NaN
2594,Porsche,Panamera S,2012,Unknown,NaN
2597,Chrysler,200 Limited,2015,Unknown,NaN
2602,Lotus,Elise Base,2005,Unknown,NaN
2641,Chevrolet,Suburban LTZ,2016,Unknown,NaN
2643,BMW,M3 Base,2012,Unknown,NaN
2649,Honda,Civic Sport,2020,Unknown,NaN
2760,Jeep,Gladiator Overland,2020,Unknown,NaN
2805,Porsche,911 Carrera Cabriolet,2001,Unknown,NaN
2821,Porsche,Boxster Base,1997,Unknown,NaN
2857,Toyota,Camry Solara SE,2008,Unknown,NaN
2876,Lincoln,Navigator L Reserve,2019,Unknown,NaN
2895,Alfa,Romeo Giulia Ti,2017,Unknown,NaN
2911,Ford,F-150 Lariat,2021,Unknown,NaN
2968,Dodge,Challenger SRT Demon,2018,Unknown,NaN
3010,Honda,Pilot EX-L,2020,Unknown,NaN
3025,Mercedes-Benz,CLS-Class CLS 63 AMG S-Model 4MATIC,2014,Unknown,NaN
3031,GMC,Sierra 2500 AT4,2022,Unknown,NaN
3103,Jeep,Grand Cherokee L Laredo,2021,Unknown,NaN
3172,Chevrolet,Caprice Classic Base,1996,Unknown,NaN
3179,Rolls-Royce,Wraith Base,2016,Unknown,NaN
3183,Toyota,Tundra TRD Pro,2016,Unknown,NaN
3209,Ford,Explorer ST,2022,Unknown,NaN
3318,Ford,Bronco Outer Banks,2023,Unknown,NaN
3433,Porsche,911 Turbo,2021,Unknown,NaN
3465,Porsche,911 Carrera C4S,2006,Unknown,NaN
3575,Porsche,911 Carrera,2021,Unknown,NaN
3670,Cadillac,XLR V,2008,Unknown,NaN
3677,Porsche,Boxster Base,2005,Unknown,NaN
3681,Alfa,Romeo Giulia Ti,2020,Unknown,NaN
3707,Porsche,718 Cayman GT4,2021,Unknown,NaN
3768,GMC,HUMMER EV Edition 1,2023,Unknown,NaN
3794,Ford,Thunderbird Deluxe,2004,Unknown,NaN
3817,Ford,F-250 King Ranch,2021,Unknown,NaN
3836,Audi,S6 4.0T Prestige,2013,Unknown,NaN
3861,Ford,Escape SEL,2020,Unknown,NaN
3865,Alfa,Romeo Giulia Quadrifoglio,2018,Unknown,NaN
3901,Mazda,CX-5 Grand Touring,2021,Unknown,NaN
3918,Porsche,911 Carrera Cabriolet,1996,Unknown,NaN
3993,Porsche,911 Carrera S,2021,Unknown,NaN
3996,Aston,Martin DB7 Vantage Volante,2003,Unknown,NaN

In [286]:
df['accident'] = df['accident'].fillna('Unknown')

In [289]:
df['accident'].head(100)

0     At least 1 accident or damage reported
1     At least 1 accident or damage reported
2                              None reported
3                              None reported
4                              None reported
5                              None reported
6                              None reported
7                              None reported
8                              None reported
9                              None reported
10                             None reported
11                             None reported
12                             None reported
13                             None reported
14                             None reported
15                             None reported
16                             None reported
17                             None reported
18                             None reported
19                             None reported
20                                   Unknown
21                             None reported
22                             None reported
23                             None reported
24                             None reported
25                             None reported
26                             None reported
27                             None reported
28                             None reported
29                             None reported
30                             None reported
31    At least 1 accident or damage reported
32                             None reported
33                             None reported
34                             None reported
35                             None reported
36                             None reported
37                             None reported
38                             None reported
39    At least 1 accident or damage reported
40                             None reported
41                             None reported
42    At least 1 accident or damage reported
43                             None reported
44                             None reported
45    At least 1 accident or damage reported
46                             None reported
47    At least 1 accident or damage reported
48                             None reported
49                             None reported
50    At least 1 accident or damage reported
51    At least 1 accident or damage reported
52                             None reported
53                             None reported
54                             None reported
55                             None reported
56                             None reported
57                             None reported
58                             None reported
59                             None reported
60                             None reported
61                             None reported
62    At least 1 accident or damage reported
63                             None reported
64                             None reported
65                             None reported
66                             None reported
67                             None reported
68                             None reported
69                             None reported
70    At least 1 accident or damage reported
71                             None reported
72                             None reported
73                             None reported
74    At least 1 accident or damage reported
75                             None reported
76                             None reported
77                             None reported
78    At least 1 accident or damage reported
79                             None reported
80                             None reported
81                             None reported
82                             None reported
83                             None reported
84    At least 1 accident or damage reported
85    At least 1 accident or damage reported
86                             None reported
87    At least 1 accident or damage reported
88                             None reported
89                                   Unknown
90                             None reported
91                             None reported
92                             None reported
93                             None reported
94    At least 1 accident or damage reported
95                             None reported
96                             None reported
97                             None reported
98                             None reported
99    At least 1 accident or damage reported
Name: accident, dtype: str

In [290]:
missing_info={}
for col in Categorical_Columns:
    if df[col].isnull().sum()>0:
        missing_count=(df[col].isnull().sum()/len(df))*100
        missing_info[col]=round(missing_count,2)
print("\n The Categorical columns with missing percentage is:\n")
for col,per in missing_info.items():
    print(f"{col}: {per}%")

 The Categorical columns with missing percentage is: